// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Button}
 */
public final class Button extends
        com.google.protobuf.GeneratedMessageLite<
                Button, Button.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.Button)
        ButtonOrBuilder {
    private Button() {
        text_ = "";
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private String text_;

    /**
     * <code>optional string text = 1;</code>
     *
     * @return Whether the text field is set.
     */
    @Override
    public boolean hasText() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional string text = 1;</code>
     *
     * @return The text.
     */
    @Override
    public String getText() {
        return text_;
    }

    /**
     * <code>optional string text = 1;</code>
     *
     * @return The bytes for text.
     */
    @Override
    public com.google.protobuf.ByteString
    getTextBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(text_);
    }

    /**
     * <code>optional string text = 1;</code>
     *
     * @param value The text to set.
     */
    private void setText(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000001;
        text_ = value;
    }

    /**
     * <code>optional string text = 1;</code>
     */
    private void clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
    }

    /**
     * <code>optional string text = 1;</code>
     *
     * @param value The bytes for text to set.
     */
    private void setTextBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        text_ = value.toStringUtf8();
        bitField0_ |= 0x00000001;
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     *
     * @return Whether the action field is set.
     */
    @Override
    public boolean hasAction() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     *
     * @return The enum numeric value on the wire for action.
     */
    @Override
    public int getActionValue() {
        return action_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     *
     * @return The action.
     */
    @Override
    public ToastFunctionType getAction() {
        ToastFunctionType result = ToastFunctionType.forNumber(action_);
        return result == null ? ToastFunctionType.UNRECOGNIZED : result;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     *
     * @param value The enum numeric value on the wire for action to set.
     */
    private void setActionValue(int value) {
        bitField0_ |= 0x00000002;
        action_ = value;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     *
     * @param value The action to set.
     */
    private void setAction(ToastFunctionType value) {
        action_ = value.getNumber();
        bitField0_ |= 0x00000002;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     */
    private void clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = 0;
    }

    public static Button parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Button parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Button parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Button parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Button parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Button parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Button parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Button parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Button parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Button parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Button parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Button parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(Button prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Button}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    Button, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.Button)
            ButtonOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.Button.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional string text = 1;</code>
         *
         * @return Whether the text field is set.
         */
        @Override
        public boolean hasText() {
            return instance.hasText();
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @return The text.
         */
        @Override
        public String getText() {
            return instance.getText();
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @return The bytes for text.
         */
        @Override
        public com.google.protobuf.ByteString
        getTextBytes() {
            return instance.getTextBytes();
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @param value The text to set.
         * @return This builder for chaining.
         */
        public Builder setText(
                String value) {
            copyOnWrite();
            instance.setText(value);
            return this;
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearText() {
            copyOnWrite();
            instance.clearText();
            return this;
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @param value The bytes for text to set.
         * @return This builder for chaining.
         */
        public Builder setTextBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setTextBytes(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
         *
         * @return Whether the action field is set.
         */
        @Override
        public boolean hasAction() {
            return instance.hasAction();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
         *
         * @return The enum numeric value on the wire for action.
         */
        @Override
        public int getActionValue() {
            return instance.getActionValue();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
         *
         * @param value The action to set.
         * @return This builder for chaining.
         */
        public Builder setActionValue(int value) {
            copyOnWrite();
            instance.setActionValue(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
         *
         * @return The action.
         */
        @Override
        public ToastFunctionType getAction() {
            return instance.getAction();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
         *
         * @param value The enum numeric value on the wire for action to set.
         * @return This builder for chaining.
         */
        public Builder setAction(ToastFunctionType value) {
            copyOnWrite();
            instance.setAction(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAction() {
            copyOnWrite();
            instance.clearAction();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.Button)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new Button();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "text_",
                        "action_",
                };
                String info =
                        "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1208\u0000\u0002" +
                                "\u100c\u0001";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<Button> parser = PARSER;
                if (parser == null) {
                    synchronized (Button.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<Button>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.Button)
    private static final Button DEFAULT_INSTANCE;

    static {
        Button defaultInstance = new Button();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                Button.class, defaultInstance);
    }

    public static Button getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Button> PARSER;

    public static com.google.protobuf.Parser<Button> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

