// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface ButtonOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.Button)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string text = 1;</code>
     *
     * @return Whether the text field is set.
     */
    boolean hasText();

    /**
     * <code>optional string text = 1;</code>
     *
     * @return The text.
     */
    String getText();

    /**
     * <code>optional string text = 1;</code>
     *
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
    getTextBytes();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     *
     * @return Whether the action field is set.
     */
    boolean hasAction();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     *
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ToastFunctionType action = 2;</code>
     *
     * @return The action.
     */
    ToastFunctionType getAction();
}
