// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface CheckBoxOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.CheckBox)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string text = 1;</code>
     *
     * @return Whether the text field is set.
     */
    boolean hasText();

    /**
     * <code>optional string text = 1;</code>
     *
     * @return The text.
     */
    String getText();

    /**
     * <code>optional string text = 1;</code>
     *
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
    getTextBytes();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckboxType type = 2;</code>
     *
     * @return Whether the type field is set.
     */
    boolean hasType();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckboxType type = 2;</code>
     *
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckboxType type = 2;</code>
     *
     * @return The type.
     */
    CheckboxType getType();

    /**
     * <code>optional bool defaultValue = 3;</code>
     *
     * @return Whether the defaultValue field is set.
     */
    boolean hasDefaultValue();

    /**
     * <code>optional bool defaultValue = 3;</code>
     *
     * @return The defaultValue.
     */
    boolean getDefaultValue();

    /**
     * <code>optional bool show = 4;</code>
     *
     * @return Whether the show field is set.
     */
    boolean hasShow();

    /**
     * <code>optional bool show = 4;</code>
     *
     * @return The show.
     */
    boolean getShow();
}
