// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf enum {@code com.muedsa.bilibililiveapiclient.model.CheckboxType}
 */
public enum CheckboxType
        implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>CheckboxTypeNone = 0;</code>
     */
    CheckboxTypeNone(0),
    /**
     * <code>CheckboxTypeEncourage = 1;</code>
     */
    CheckboxTypeEncourage(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CheckboxTypeNone = 0;</code>
     */
    public static final int CheckboxTypeNone_VALUE = 0;
    /**
     * <code>CheckboxTypeEncourage = 1;</code>
     */
    public static final int CheckboxTypeEncourage_VALUE = 1;


    @Override
    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CheckboxType valueOf(int value) {
        return forNumber(value);
    }

    public static CheckboxType forNumber(int value) {
        switch (value) {
            case 0:
                return CheckboxTypeNone;
            case 1:
                return CheckboxTypeEncourage;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CheckboxType>
    internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            CheckboxType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CheckboxType>() {
                @Override
                public CheckboxType findValueByNumber(int number) {
                    return CheckboxType.forNumber(number);
                }
            };

    public static com.google.protobuf.Internal.EnumVerifier
    internalGetVerifier() {
        return CheckboxTypeVerifier.INSTANCE;
    }

    private static final class CheckboxTypeVerifier implements
            com.google.protobuf.Internal.EnumVerifier {
        static final com.google.protobuf.Internal.EnumVerifier INSTANCE = new CheckboxTypeVerifier();

        @Override
        public boolean isInRange(int number) {
            return CheckboxType.forNumber(number) != null;
        }
    }

    ;

    private final int value;

    private CheckboxType(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.muedsa.bilibililiveapiclient.model.CheckboxType)
}

