// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface ClickButtonOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.ClickButton)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @return A list containing the portraitText.
     */
    java.util.List<String>
    getPortraitTextList();

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @return The count of portraitText.
     */
    int getPortraitTextCount();

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The portraitText at the given index.
     */
    String getPortraitText(int index);

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The portraitText at the given index.
     */
    com.google.protobuf.ByteString
    getPortraitTextBytes(int index);

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @return A list containing the landscapeText.
     */
    java.util.List<String>
    getLandscapeTextList();

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @return The count of landscapeText.
     */
    int getLandscapeTextCount();

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The landscapeText at the given index.
     */
    String getLandscapeText(int index);

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The landscapeText at the given index.
     */
    com.google.protobuf.ByteString
    getLandscapeTextBytes(int index);

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @return A list containing the portraitTextFocus.
     */
    java.util.List<String>
    getPortraitTextFocusList();

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @return The count of portraitTextFocus.
     */
    int getPortraitTextFocusCount();

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The portraitTextFocus at the given index.
     */
    String getPortraitTextFocus(int index);

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The portraitTextFocus at the given index.
     */
    com.google.protobuf.ByteString
    getPortraitTextFocusBytes(int index);

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @return A list containing the landscapeTextFocus.
     */
    java.util.List<String>
    getLandscapeTextFocusList();

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @return The count of landscapeTextFocus.
     */
    int getLandscapeTextFocusCount();

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @param index The index of the element to return.
     * @return The landscapeTextFocus at the given index.
     */
    String getLandscapeTextFocus(int index);

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @param index The index of the element to return.
     * @return The landscapeTextFocus at the given index.
     */
    com.google.protobuf.ByteString
    getLandscapeTextFocusBytes(int index);

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     *
     * @return Whether the renderType field is set.
     */
    boolean hasRenderType();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     *
     * @return The enum numeric value on the wire for renderType.
     */
    int getRenderTypeValue();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     *
     * @return The renderType.
     */
    RenderType getRenderType();

    /**
     * <code>optional bool show = 6;</code>
     *
     * @return Whether the show field is set.
     */
    boolean hasShow();

    /**
     * <code>optional bool show = 6;</code>
     *
     * @return The show.
     */
    boolean getShow();
}
