// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.ClickButton}
 */
public final class ClickButton extends
        com.google.protobuf.GeneratedMessageLite<
                ClickButton, ClickButton.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.ClickButton)
        ClickButtonOrBuilder {
    private ClickButton() {
        portraitText_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        landscapeText_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        portraitTextFocus_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        landscapeTextFocus_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    private int bitField0_;
    public static final int PORTRAITTEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<String> portraitText_;

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @return A list containing the portraitText.
     */
    @Override
    public java.util.List<String> getPortraitTextList() {
        return portraitText_;
    }

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @return The count of portraitText.
     */
    @Override
    public int getPortraitTextCount() {
        return portraitText_.size();
    }

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The portraitText at the given index.
     */
    @Override
    public String getPortraitText(int index) {
        return portraitText_.get(index);
    }

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the portraitText at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
    getPortraitTextBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
                portraitText_.get(index));
    }

    private void ensurePortraitTextIsMutable() {
        com.google.protobuf.Internal.ProtobufList<String> tmp =
                portraitText_;
        if (!tmp.isModifiable()) {
            portraitText_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @param index The index to set the value at.
     * @param value The portraitText to set.
     */
    private void setPortraitText(
            int index, String value) {
        Class<?> valueClass = value.getClass();
        ensurePortraitTextIsMutable();
        portraitText_.set(index, value);
    }

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @param value The portraitText to add.
     */
    private void addPortraitText(
            String value) {
        Class<?> valueClass = value.getClass();
        ensurePortraitTextIsMutable();
        portraitText_.add(value);
    }

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @param values The portraitText to add.
     */
    private void addAllPortraitText(
            Iterable<String> values) {
        ensurePortraitTextIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, portraitText_);
    }

    /**
     * <code>repeated string portraitText = 1;</code>
     */
    private void clearPortraitText() {
        portraitText_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    /**
     * <code>repeated string portraitText = 1;</code>
     *
     * @param value The bytes of the portraitText to add.
     */
    private void addPortraitTextBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensurePortraitTextIsMutable();
        portraitText_.add(value.toStringUtf8());
    }

    public static final int LANDSCAPETEXT_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<String> landscapeText_;

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @return A list containing the landscapeText.
     */
    @Override
    public java.util.List<String> getLandscapeTextList() {
        return landscapeText_;
    }

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @return The count of landscapeText.
     */
    @Override
    public int getLandscapeTextCount() {
        return landscapeText_.size();
    }

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The landscapeText at the given index.
     */
    @Override
    public String getLandscapeText(int index) {
        return landscapeText_.get(index);
    }

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the landscapeText at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
    getLandscapeTextBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
                landscapeText_.get(index));
    }

    private void ensureLandscapeTextIsMutable() {
        com.google.protobuf.Internal.ProtobufList<String> tmp =
                landscapeText_;
        if (!tmp.isModifiable()) {
            landscapeText_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @param index The index to set the value at.
     * @param value The landscapeText to set.
     */
    private void setLandscapeText(
            int index, String value) {
        Class<?> valueClass = value.getClass();
        ensureLandscapeTextIsMutable();
        landscapeText_.set(index, value);
    }

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @param value The landscapeText to add.
     */
    private void addLandscapeText(
            String value) {
        Class<?> valueClass = value.getClass();
        ensureLandscapeTextIsMutable();
        landscapeText_.add(value);
    }

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @param values The landscapeText to add.
     */
    private void addAllLandscapeText(
            Iterable<String> values) {
        ensureLandscapeTextIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, landscapeText_);
    }

    /**
     * <code>repeated string landscapeText = 2;</code>
     */
    private void clearLandscapeText() {
        landscapeText_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    /**
     * <code>repeated string landscapeText = 2;</code>
     *
     * @param value The bytes of the landscapeText to add.
     */
    private void addLandscapeTextBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensureLandscapeTextIsMutable();
        landscapeText_.add(value.toStringUtf8());
    }

    public static final int PORTRAITTEXTFOCUS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<String> portraitTextFocus_;

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @return A list containing the portraitTextFocus.
     */
    @Override
    public java.util.List<String> getPortraitTextFocusList() {
        return portraitTextFocus_;
    }

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @return The count of portraitTextFocus.
     */
    @Override
    public int getPortraitTextFocusCount() {
        return portraitTextFocus_.size();
    }

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @param index The index of the element to return.
     * @return The portraitTextFocus at the given index.
     */
    @Override
    public String getPortraitTextFocus(int index) {
        return portraitTextFocus_.get(index);
    }

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the portraitTextFocus at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
    getPortraitTextFocusBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
                portraitTextFocus_.get(index));
    }

    private void ensurePortraitTextFocusIsMutable() {
        com.google.protobuf.Internal.ProtobufList<String> tmp =
                portraitTextFocus_;
        if (!tmp.isModifiable()) {
            portraitTextFocus_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @param index The index to set the value at.
     * @param value The portraitTextFocus to set.
     */
    private void setPortraitTextFocus(
            int index, String value) {
        Class<?> valueClass = value.getClass();
        ensurePortraitTextFocusIsMutable();
        portraitTextFocus_.set(index, value);
    }

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @param value The portraitTextFocus to add.
     */
    private void addPortraitTextFocus(
            String value) {
        Class<?> valueClass = value.getClass();
        ensurePortraitTextFocusIsMutable();
        portraitTextFocus_.add(value);
    }

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @param values The portraitTextFocus to add.
     */
    private void addAllPortraitTextFocus(
            Iterable<String> values) {
        ensurePortraitTextFocusIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, portraitTextFocus_);
    }

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     */
    private void clearPortraitTextFocus() {
        portraitTextFocus_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    /**
     * <code>repeated string portraitTextFocus = 3;</code>
     *
     * @param value The bytes of the portraitTextFocus to add.
     */
    private void addPortraitTextFocusBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensurePortraitTextFocusIsMutable();
        portraitTextFocus_.add(value.toStringUtf8());
    }

    public static final int LANDSCAPETEXTFOCUS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<String> landscapeTextFocus_;

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @return A list containing the landscapeTextFocus.
     */
    @Override
    public java.util.List<String> getLandscapeTextFocusList() {
        return landscapeTextFocus_;
    }

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @return The count of landscapeTextFocus.
     */
    @Override
    public int getLandscapeTextFocusCount() {
        return landscapeTextFocus_.size();
    }

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @param index The index of the element to return.
     * @return The landscapeTextFocus at the given index.
     */
    @Override
    public String getLandscapeTextFocus(int index) {
        return landscapeTextFocus_.get(index);
    }

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the landscapeTextFocus at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
    getLandscapeTextFocusBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
                landscapeTextFocus_.get(index));
    }

    private void ensureLandscapeTextFocusIsMutable() {
        com.google.protobuf.Internal.ProtobufList<String> tmp =
                landscapeTextFocus_;
        if (!tmp.isModifiable()) {
            landscapeTextFocus_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @param index The index to set the value at.
     * @param value The landscapeTextFocus to set.
     */
    private void setLandscapeTextFocus(
            int index, String value) {
        Class<?> valueClass = value.getClass();
        ensureLandscapeTextFocusIsMutable();
        landscapeTextFocus_.set(index, value);
    }

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @param value The landscapeTextFocus to add.
     */
    private void addLandscapeTextFocus(
            String value) {
        Class<?> valueClass = value.getClass();
        ensureLandscapeTextFocusIsMutable();
        landscapeTextFocus_.add(value);
    }

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @param values The landscapeTextFocus to add.
     */
    private void addAllLandscapeTextFocus(
            Iterable<String> values) {
        ensureLandscapeTextFocusIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, landscapeTextFocus_);
    }

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     */
    private void clearLandscapeTextFocus() {
        landscapeTextFocus_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    /**
     * <code>repeated string landscapeTextFocus = 4;</code>
     *
     * @param value The bytes of the landscapeTextFocus to add.
     */
    private void addLandscapeTextFocusBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensureLandscapeTextFocusIsMutable();
        landscapeTextFocus_.add(value.toStringUtf8());
    }

    public static final int RENDERTYPE_FIELD_NUMBER = 5;
    private int renderType_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     *
     * @return Whether the renderType field is set.
     */
    @Override
    public boolean hasRenderType() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     *
     * @return The enum numeric value on the wire for renderType.
     */
    @Override
    public int getRenderTypeValue() {
        return renderType_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     *
     * @return The renderType.
     */
    @Override
    public RenderType getRenderType() {
        RenderType result = RenderType.forNumber(renderType_);
        return result == null ? RenderType.UNRECOGNIZED : result;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     *
     * @param value The enum numeric value on the wire for renderType to set.
     */
    private void setRenderTypeValue(int value) {
        bitField0_ |= 0x00000001;
        renderType_ = value;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     *
     * @param value The renderType to set.
     */
    private void setRenderType(RenderType value) {
        renderType_ = value.getNumber();
        bitField0_ |= 0x00000001;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
     */
    private void clearRenderType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        renderType_ = 0;
    }

    public static final int SHOW_FIELD_NUMBER = 6;
    private boolean show_;

    /**
     * <code>optional bool show = 6;</code>
     *
     * @return Whether the show field is set.
     */
    @Override
    public boolean hasShow() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional bool show = 6;</code>
     *
     * @return The show.
     */
    @Override
    public boolean getShow() {
        return show_;
    }

    /**
     * <code>optional bool show = 6;</code>
     *
     * @param value The show to set.
     */
    private void setShow(boolean value) {
        bitField0_ |= 0x00000002;
        show_ = value;
    }

    /**
     * <code>optional bool show = 6;</code>
     */
    private void clearShow() {
        bitField0_ = (bitField0_ & ~0x00000002);
        show_ = false;
    }

    public static ClickButton parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static ClickButton parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static ClickButton parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static ClickButton parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static ClickButton parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static ClickButton parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static ClickButton parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static ClickButton parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static ClickButton parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static ClickButton parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static ClickButton parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static ClickButton parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(ClickButton prototype) {
        return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.ClickButton}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    ClickButton, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.ClickButton)
            ClickButtonOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.ClickButton.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @return A list containing the portraitText.
         */
        @Override
        public java.util.List<String>
        getPortraitTextList() {
            return java.util.Collections.unmodifiableList(
                    instance.getPortraitTextList());
        }

        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @return The count of portraitText.
         */
        @Override
        public int getPortraitTextCount() {
            return instance.getPortraitTextCount();
        }

        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The portraitText at the given index.
         */
        @Override
        public String getPortraitText(int index) {
            return instance.getPortraitText(index);
        }

        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the portraitText at the given index.
         */
        @Override
        public com.google.protobuf.ByteString
        getPortraitTextBytes(int index) {
            return instance.getPortraitTextBytes(index);
        }

        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @param index The index to set the value at.
         * @param value The portraitText to set.
         * @return This builder for chaining.
         */
        public Builder setPortraitText(
                int index, String value) {
            copyOnWrite();
            instance.setPortraitText(index, value);
            return this;
        }

        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @param value The portraitText to add.
         * @return This builder for chaining.
         */
        public Builder addPortraitText(
                String value) {
            copyOnWrite();
            instance.addPortraitText(value);
            return this;
        }

        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @param values The portraitText to add.
         * @return This builder for chaining.
         */
        public Builder addAllPortraitText(
                Iterable<String> values) {
            copyOnWrite();
            instance.addAllPortraitText(values);
            return this;
        }

        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPortraitText() {
            copyOnWrite();
            instance.clearPortraitText();
            return this;
        }

        /**
         * <code>repeated string portraitText = 1;</code>
         *
         * @param value The bytes of the portraitText to add.
         * @return This builder for chaining.
         */
        public Builder addPortraitTextBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.addPortraitTextBytes(value);
            return this;
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @return A list containing the landscapeText.
         */
        @Override
        public java.util.List<String>
        getLandscapeTextList() {
            return java.util.Collections.unmodifiableList(
                    instance.getLandscapeTextList());
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @return The count of landscapeText.
         */
        @Override
        public int getLandscapeTextCount() {
            return instance.getLandscapeTextCount();
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @param index The index of the element to return.
         * @return The landscapeText at the given index.
         */
        @Override
        public String getLandscapeText(int index) {
            return instance.getLandscapeText(index);
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the landscapeText at the given index.
         */
        @Override
        public com.google.protobuf.ByteString
        getLandscapeTextBytes(int index) {
            return instance.getLandscapeTextBytes(index);
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @param index The index to set the value at.
         * @param value The landscapeText to set.
         * @return This builder for chaining.
         */
        public Builder setLandscapeText(
                int index, String value) {
            copyOnWrite();
            instance.setLandscapeText(index, value);
            return this;
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @param value The landscapeText to add.
         * @return This builder for chaining.
         */
        public Builder addLandscapeText(
                String value) {
            copyOnWrite();
            instance.addLandscapeText(value);
            return this;
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @param values The landscapeText to add.
         * @return This builder for chaining.
         */
        public Builder addAllLandscapeText(
                Iterable<String> values) {
            copyOnWrite();
            instance.addAllLandscapeText(values);
            return this;
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLandscapeText() {
            copyOnWrite();
            instance.clearLandscapeText();
            return this;
        }

        /**
         * <code>repeated string landscapeText = 2;</code>
         *
         * @param value The bytes of the landscapeText to add.
         * @return This builder for chaining.
         */
        public Builder addLandscapeTextBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.addLandscapeTextBytes(value);
            return this;
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @return A list containing the portraitTextFocus.
         */
        @Override
        public java.util.List<String>
        getPortraitTextFocusList() {
            return java.util.Collections.unmodifiableList(
                    instance.getPortraitTextFocusList());
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @return The count of portraitTextFocus.
         */
        @Override
        public int getPortraitTextFocusCount() {
            return instance.getPortraitTextFocusCount();
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The portraitTextFocus at the given index.
         */
        @Override
        public String getPortraitTextFocus(int index) {
            return instance.getPortraitTextFocus(index);
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the portraitTextFocus at the given index.
         */
        @Override
        public com.google.protobuf.ByteString
        getPortraitTextFocusBytes(int index) {
            return instance.getPortraitTextFocusBytes(index);
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @param index The index to set the value at.
         * @param value The portraitTextFocus to set.
         * @return This builder for chaining.
         */
        public Builder setPortraitTextFocus(
                int index, String value) {
            copyOnWrite();
            instance.setPortraitTextFocus(index, value);
            return this;
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @param value The portraitTextFocus to add.
         * @return This builder for chaining.
         */
        public Builder addPortraitTextFocus(
                String value) {
            copyOnWrite();
            instance.addPortraitTextFocus(value);
            return this;
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @param values The portraitTextFocus to add.
         * @return This builder for chaining.
         */
        public Builder addAllPortraitTextFocus(
                Iterable<String> values) {
            copyOnWrite();
            instance.addAllPortraitTextFocus(values);
            return this;
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPortraitTextFocus() {
            copyOnWrite();
            instance.clearPortraitTextFocus();
            return this;
        }

        /**
         * <code>repeated string portraitTextFocus = 3;</code>
         *
         * @param value The bytes of the portraitTextFocus to add.
         * @return This builder for chaining.
         */
        public Builder addPortraitTextFocusBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.addPortraitTextFocusBytes(value);
            return this;
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @return A list containing the landscapeTextFocus.
         */
        @Override
        public java.util.List<String>
        getLandscapeTextFocusList() {
            return java.util.Collections.unmodifiableList(
                    instance.getLandscapeTextFocusList());
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @return The count of landscapeTextFocus.
         */
        @Override
        public int getLandscapeTextFocusCount() {
            return instance.getLandscapeTextFocusCount();
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The landscapeTextFocus at the given index.
         */
        @Override
        public String getLandscapeTextFocus(int index) {
            return instance.getLandscapeTextFocus(index);
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the landscapeTextFocus at the given index.
         */
        @Override
        public com.google.protobuf.ByteString
        getLandscapeTextFocusBytes(int index) {
            return instance.getLandscapeTextFocusBytes(index);
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @param index The index to set the value at.
         * @param value The landscapeTextFocus to set.
         * @return This builder for chaining.
         */
        public Builder setLandscapeTextFocus(
                int index, String value) {
            copyOnWrite();
            instance.setLandscapeTextFocus(index, value);
            return this;
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @param value The landscapeTextFocus to add.
         * @return This builder for chaining.
         */
        public Builder addLandscapeTextFocus(
                String value) {
            copyOnWrite();
            instance.addLandscapeTextFocus(value);
            return this;
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @param values The landscapeTextFocus to add.
         * @return This builder for chaining.
         */
        public Builder addAllLandscapeTextFocus(
                Iterable<String> values) {
            copyOnWrite();
            instance.addAllLandscapeTextFocus(values);
            return this;
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLandscapeTextFocus() {
            copyOnWrite();
            instance.clearLandscapeTextFocus();
            return this;
        }

        /**
         * <code>repeated string landscapeTextFocus = 4;</code>
         *
         * @param value The bytes of the landscapeTextFocus to add.
         * @return This builder for chaining.
         */
        public Builder addLandscapeTextFocusBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.addLandscapeTextFocusBytes(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
         *
         * @return Whether the renderType field is set.
         */
        @Override
        public boolean hasRenderType() {
            return instance.hasRenderType();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
         *
         * @return The enum numeric value on the wire for renderType.
         */
        @Override
        public int getRenderTypeValue() {
            return instance.getRenderTypeValue();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
         *
         * @param value The renderType to set.
         * @return This builder for chaining.
         */
        public Builder setRenderTypeValue(int value) {
            copyOnWrite();
            instance.setRenderTypeValue(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
         *
         * @return The renderType.
         */
        @Override
        public RenderType getRenderType() {
            return instance.getRenderType();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
         *
         * @param value The enum numeric value on the wire for renderType to set.
         * @return This builder for chaining.
         */
        public Builder setRenderType(RenderType value) {
            copyOnWrite();
            instance.setRenderType(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearRenderType() {
            copyOnWrite();
            instance.clearRenderType();
            return this;
        }

        /**
         * <code>optional bool show = 6;</code>
         *
         * @return Whether the show field is set.
         */
        @Override
        public boolean hasShow() {
            return instance.hasShow();
        }

        /**
         * <code>optional bool show = 6;</code>
         *
         * @return The show.
         */
        @Override
        public boolean getShow() {
            return instance.getShow();
        }

        /**
         * <code>optional bool show = 6;</code>
         *
         * @param value The show to set.
         * @return This builder for chaining.
         */
        public Builder setShow(boolean value) {
            copyOnWrite();
            instance.setShow(value);
            return this;
        }

        /**
         * <code>optional bool show = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearShow() {
            copyOnWrite();
            instance.clearShow();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.ClickButton)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new ClickButton();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "portraitText_",
                        "landscapeText_",
                        "portraitTextFocus_",
                        "landscapeTextFocus_",
                        "renderType_",
                        "show_",
                };
                String info =
                        "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0004\u0000\u0001\u021a\u0002\u021a" +
                                "\u0003\u021a\u0004\u021a\u0005\u100c\u0000\u0006\u1007\u0001";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<ClickButton> parser = PARSER;
                if (parser == null) {
                    synchronized (ClickButton.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<ClickButton>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.ClickButton)
    private static final ClickButton DEFAULT_INSTANCE;

    static {
        ClickButton defaultInstance = new ClickButton();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                ClickButton.class, defaultInstance);
    }

    public static ClickButton getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ClickButton> PARSER;

    public static com.google.protobuf.Parser<ClickButton> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

