// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface CommandDmOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.CommandDm)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     *
     * @return Whether the id field is set.
     */
    boolean hasId();

    /**
     * <code>optional int64 id = 1;</code>
     *
     * @return The id.
     */
    long getId();

    /**
     * <code>optional int64 oid = 2;</code>
     *
     * @return Whether the oid field is set.
     */
    boolean hasOid();

    /**
     * <code>optional int64 oid = 2;</code>
     *
     * @return The oid.
     */
    long getOid();

    /**
     * <code>optional int64 mid = 3;</code>
     *
     * @return Whether the mid field is set.
     */
    boolean hasMid();

    /**
     * <code>optional int64 mid = 3;</code>
     *
     * @return The mid.
     */
    long getMid();

    /**
     * <code>optional int64 command = 4;</code>
     *
     * @return Whether the command field is set.
     */
    boolean hasCommand();

    /**
     * <code>optional int64 command = 4;</code>
     *
     * @return The command.
     */
    long getCommand();

    /**
     * <code>optional string content = 5;</code>
     *
     * @return Whether the content field is set.
     */
    boolean hasContent();

    /**
     * <code>optional string content = 5;</code>
     *
     * @return The content.
     */
    String getContent();

    /**
     * <code>optional string content = 5;</code>
     *
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
    getContentBytes();

    /**
     * <code>optional int32 progress = 6;</code>
     *
     * @return Whether the progress field is set.
     */
    boolean hasProgress();

    /**
     * <code>optional int32 progress = 6;</code>
     *
     * @return The progress.
     */
    int getProgress();

    /**
     * <code>optional string ctime = 7;</code>
     *
     * @return Whether the ctime field is set.
     */
    boolean hasCtime();

    /**
     * <code>optional string ctime = 7;</code>
     *
     * @return The ctime.
     */
    String getCtime();

    /**
     * <code>optional string ctime = 7;</code>
     *
     * @return The bytes for ctime.
     */
    com.google.protobuf.ByteString
    getCtimeBytes();

    /**
     * <code>optional string mtime = 8;</code>
     *
     * @return Whether the mtime field is set.
     */
    boolean hasMtime();

    /**
     * <code>optional string mtime = 8;</code>
     *
     * @return The mtime.
     */
    String getMtime();

    /**
     * <code>optional string mtime = 8;</code>
     *
     * @return The bytes for mtime.
     */
    com.google.protobuf.ByteString
    getMtimeBytes();

    /**
     * <code>optional string extra = 9;</code>
     *
     * @return Whether the extra field is set.
     */
    boolean hasExtra();

    /**
     * <code>optional string extra = 9;</code>
     *
     * @return The extra.
     */
    String getExtra();

    /**
     * <code>optional string extra = 9;</code>
     *
     * @return The bytes for extra.
     */
    com.google.protobuf.ByteString
    getExtraBytes();

    /**
     * <code>optional string idStr = 10;</code>
     *
     * @return Whether the idStr field is set.
     */
    boolean hasIdStr();

    /**
     * <code>optional string idStr = 10;</code>
     *
     * @return The idStr.
     */
    String getIdStr();

    /**
     * <code>optional string idStr = 10;</code>
     *
     * @return The bytes for idStr.
     */
    com.google.protobuf.ByteString
    getIdStrBytes();
}
