// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface DanmakuElemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.DanmakuElem)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 id = 1;</code>
     *
     * @return Whether the id field is set.
     */
    boolean hasId();

    /**
     * <code>optional int64 id = 1;</code>
     *
     * @return The id.
     */
    long getId();

    /**
     * <code>optional int32 progress = 2;</code>
     *
     * @return Whether the progress field is set.
     */
    boolean hasProgress();

    /**
     * <code>optional int32 progress = 2;</code>
     *
     * @return The progress.
     */
    int getProgress();

    /**
     * <code>optional int32 mode = 3;</code>
     *
     * @return Whether the mode field is set.
     */
    boolean hasMode();

    /**
     * <code>optional int32 mode = 3;</code>
     *
     * @return The mode.
     */
    int getMode();

    /**
     * <code>optional int32 fontSize = 4;</code>
     *
     * @return Whether the fontSize field is set.
     */
    boolean hasFontSize();

    /**
     * <code>optional int32 fontSize = 4;</code>
     *
     * @return The fontSize.
     */
    int getFontSize();

    /**
     * <code>optional uint32 color = 5;</code>
     *
     * @return Whether the color field is set.
     */
    boolean hasColor();

    /**
     * <code>optional uint32 color = 5;</code>
     *
     * @return The color.
     */
    int getColor();

    /**
     * <code>optional string midHash = 6;</code>
     *
     * @return Whether the midHash field is set.
     */
    boolean hasMidHash();

    /**
     * <code>optional string midHash = 6;</code>
     *
     * @return The midHash.
     */
    String getMidHash();

    /**
     * <code>optional string midHash = 6;</code>
     *
     * @return The bytes for midHash.
     */
    com.google.protobuf.ByteString
    getMidHashBytes();

    /**
     * <code>optional string content = 7;</code>
     *
     * @return Whether the content field is set.
     */
    boolean hasContent();

    /**
     * <code>optional string content = 7;</code>
     *
     * @return The content.
     */
    String getContent();

    /**
     * <code>optional string content = 7;</code>
     *
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
    getContentBytes();

    /**
     * <code>optional int64 ctime = 8;</code>
     *
     * @return Whether the ctime field is set.
     */
    boolean hasCtime();

    /**
     * <code>optional int64 ctime = 8;</code>
     *
     * @return The ctime.
     */
    long getCtime();

    /**
     * <code>optional int32 weight = 9;</code>
     *
     * @return Whether the weight field is set.
     */
    boolean hasWeight();

    /**
     * <code>optional int32 weight = 9;</code>
     *
     * @return The weight.
     */
    int getWeight();

    /**
     * <code>optional string action = 10;</code>
     *
     * @return Whether the action field is set.
     */
    boolean hasAction();

    /**
     * <code>optional string action = 10;</code>
     *
     * @return The action.
     */
    String getAction();

    /**
     * <code>optional string action = 10;</code>
     *
     * @return The bytes for action.
     */
    com.google.protobuf.ByteString
    getActionBytes();

    /**
     * <code>optional int32 pool = 11;</code>
     *
     * @return Whether the pool field is set.
     */
    boolean hasPool();

    /**
     * <code>optional int32 pool = 11;</code>
     *
     * @return The pool.
     */
    int getPool();

    /**
     * <code>optional string idStr = 12;</code>
     *
     * @return Whether the idStr field is set.
     */
    boolean hasIdStr();

    /**
     * <code>optional string idStr = 12;</code>
     *
     * @return The idStr.
     */
    String getIdStr();

    /**
     * <code>optional string idStr = 12;</code>
     *
     * @return The bytes for idStr.
     */
    com.google.protobuf.ByteString
    getIdStrBytes();

    /**
     * <code>optional int32 attr = 13;</code>
     *
     * @return Whether the attr field is set.
     */
    boolean hasAttr();

    /**
     * <code>optional int32 attr = 13;</code>
     *
     * @return The attr.
     */
    int getAttr();

    /**
     * <code>optional string animation = 22;</code>
     *
     * @return Whether the animation field is set.
     */
    boolean hasAnimation();

    /**
     * <code>optional string animation = 22;</code>
     *
     * @return The animation.
     */
    String getAnimation();

    /**
     * <code>optional string animation = 22;</code>
     *
     * @return The bytes for animation.
     */
    com.google.protobuf.ByteString
    getAnimationBytes();
}
