// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface DanmuWebPlayerConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional bool dmSwitch = 1;</code>
     *
     * @return Whether the dmSwitch field is set.
     */
    boolean hasDmSwitch();

    /**
     * <code>optional bool dmSwitch = 1;</code>
     *
     * @return The dmSwitch.
     */
    boolean getDmSwitch();

    /**
     * <code>optional bool aiSwitch = 2;</code>
     *
     * @return Whether the aiSwitch field is set.
     */
    boolean hasAiSwitch();

    /**
     * <code>optional bool aiSwitch = 2;</code>
     *
     * @return The aiSwitch.
     */
    boolean getAiSwitch();

    /**
     * <code>optional int32 aiLevel = 3;</code>
     *
     * @return Whether the aiLevel field is set.
     */
    boolean hasAiLevel();

    /**
     * <code>optional int32 aiLevel = 3;</code>
     *
     * @return The aiLevel.
     */
    int getAiLevel();

    /**
     * <code>optional bool typeTop = 4;</code>
     *
     * @return Whether the typeTop field is set.
     */
    boolean hasTypeTop();

    /**
     * <code>optional bool typeTop = 4;</code>
     *
     * @return The typeTop.
     */
    boolean getTypeTop();

    /**
     * <code>optional bool typeScroll = 5;</code>
     *
     * @return Whether the typeScroll field is set.
     */
    boolean hasTypeScroll();

    /**
     * <code>optional bool typeScroll = 5;</code>
     *
     * @return The typeScroll.
     */
    boolean getTypeScroll();

    /**
     * <code>optional bool typeBottom = 6;</code>
     *
     * @return Whether the typeBottom field is set.
     */
    boolean hasTypeBottom();

    /**
     * <code>optional bool typeBottom = 6;</code>
     *
     * @return The typeBottom.
     */
    boolean getTypeBottom();

    /**
     * <code>optional bool typeColor = 7;</code>
     *
     * @return Whether the typeColor field is set.
     */
    boolean hasTypeColor();

    /**
     * <code>optional bool typeColor = 7;</code>
     *
     * @return The typeColor.
     */
    boolean getTypeColor();

    /**
     * <code>optional bool typeSpecial = 8;</code>
     *
     * @return Whether the typeSpecial field is set.
     */
    boolean hasTypeSpecial();

    /**
     * <code>optional bool typeSpecial = 8;</code>
     *
     * @return The typeSpecial.
     */
    boolean getTypeSpecial();

    /**
     * <code>optional bool preventShade = 9;</code>
     *
     * @return Whether the preventShade field is set.
     */
    boolean hasPreventShade();

    /**
     * <code>optional bool preventShade = 9;</code>
     *
     * @return The preventShade.
     */
    boolean getPreventShade();

    /**
     * <code>optional bool dmask = 10;</code>
     *
     * @return Whether the dmask field is set.
     */
    boolean hasDmask();

    /**
     * <code>optional bool dmask = 10;</code>
     *
     * @return The dmask.
     */
    boolean getDmask();

    /**
     * <code>optional float opacity = 11;</code>
     *
     * @return Whether the opacity field is set.
     */
    boolean hasOpacity();

    /**
     * <code>optional float opacity = 11;</code>
     *
     * @return The opacity.
     */
    float getOpacity();

    /**
     * <code>optional int32 dmArea = 12;</code>
     *
     * @return Whether the dmArea field is set.
     */
    boolean hasDmArea();

    /**
     * <code>optional int32 dmArea = 12;</code>
     *
     * @return The dmArea.
     */
    int getDmArea();

    /**
     * <code>optional float speedPlus = 13;</code>
     *
     * @return Whether the speedPlus field is set.
     */
    boolean hasSpeedPlus();

    /**
     * <code>optional float speedPlus = 13;</code>
     *
     * @return The speedPlus.
     */
    float getSpeedPlus();

    /**
     * <code>optional float fontSize = 14;</code>
     *
     * @return Whether the fontSize field is set.
     */
    boolean hasFontSize();

    /**
     * <code>optional float fontSize = 14;</code>
     *
     * @return The fontSize.
     */
    float getFontSize();

    /**
     * <code>optional bool fullScreenSync = 15;</code>
     *
     * @return Whether the fullScreenSync field is set.
     */
    boolean hasFullScreenSync();

    /**
     * <code>optional bool fullScreenSync = 15;</code>
     *
     * @return The fullScreenSync.
     */
    boolean getFullScreenSync();

    /**
     * <code>optional bool speedSync = 16;</code>
     *
     * @return Whether the speedSync field is set.
     */
    boolean hasSpeedSync();

    /**
     * <code>optional bool speedSync = 16;</code>
     *
     * @return The speedSync.
     */
    boolean getSpeedSync();

    /**
     * <code>optional string fontFamily = 17;</code>
     *
     * @return Whether the fontFamily field is set.
     */
    boolean hasFontFamily();

    /**
     * <code>optional string fontFamily = 17;</code>
     *
     * @return The fontFamily.
     */
    String getFontFamily();

    /**
     * <code>optional string fontFamily = 17;</code>
     *
     * @return The bytes for fontFamily.
     */
    com.google.protobuf.ByteString
    getFontFamilyBytes();

    /**
     * <code>optional bool bold = 18;</code>
     *
     * @return Whether the bold field is set.
     */
    boolean hasBold();

    /**
     * <code>optional bool bold = 18;</code>
     *
     * @return The bold.
     */
    boolean getBold();

    /**
     * <code>optional int32 fontBorder = 19;</code>
     *
     * @return Whether the fontBorder field is set.
     */
    boolean hasFontBorder();

    /**
     * <code>optional int32 fontBorder = 19;</code>
     *
     * @return The fontBorder.
     */
    int getFontBorder();

    /**
     * <code>optional string drawType = 20;</code>
     *
     * @return Whether the drawType field is set.
     */
    boolean hasDrawType();

    /**
     * <code>optional string drawType = 20;</code>
     *
     * @return The drawType.
     */
    String getDrawType();

    /**
     * <code>optional string drawType = 20;</code>
     *
     * @return The bytes for drawType.
     */
    com.google.protobuf.ByteString
    getDrawTypeBytes();

    /**
     * <code>optional int32 seniorModeSwitch = 21;</code>
     *
     * @return Whether the seniorModeSwitch field is set.
     */
    boolean hasSeniorModeSwitch();

    /**
     * <code>optional int32 seniorModeSwitch = 21;</code>
     *
     * @return The seniorModeSwitch.
     */
    int getSeniorModeSwitch();
}
