// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.DanmakuElem}
 */
public final class DanmakuElem extends
        com.google.protobuf.GeneratedMessageLite<
                DanmakuElem, DanmakuElem.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.DanmakuElem)
        DanmakuElemOrBuilder {
    private DanmakuElem() {
        midHash_ = "";
        content_ = "";
        action_ = "";
        idStr_ = "";
        animation_ = "";
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;

    /**
     * <code>optional int64 id = 1;</code>
     *
     * @return Whether the id field is set.
     */
    @Override
    public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional int64 id = 1;</code>
     *
     * @return The id.
     */
    @Override
    public long getId() {
        return id_;
    }

    /**
     * <code>optional int64 id = 1;</code>
     *
     * @param value The id to set.
     */
    private void setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
    }

    /**
     * <code>optional int64 id = 1;</code>
     */
    private void clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
    }

    public static final int PROGRESS_FIELD_NUMBER = 2;
    private int progress_;

    /**
     * <code>optional int32 progress = 2;</code>
     *
     * @return Whether the progress field is set.
     */
    @Override
    public boolean hasProgress() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional int32 progress = 2;</code>
     *
     * @return The progress.
     */
    @Override
    public int getProgress() {
        return progress_;
    }

    /**
     * <code>optional int32 progress = 2;</code>
     *
     * @param value The progress to set.
     */
    private void setProgress(int value) {
        bitField0_ |= 0x00000002;
        progress_ = value;
    }

    /**
     * <code>optional int32 progress = 2;</code>
     */
    private void clearProgress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        progress_ = 0;
    }

    public static final int MODE_FIELD_NUMBER = 3;
    private int mode_;

    /**
     * <code>optional int32 mode = 3;</code>
     *
     * @return Whether the mode field is set.
     */
    @Override
    public boolean hasMode() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>optional int32 mode = 3;</code>
     *
     * @return The mode.
     */
    @Override
    public int getMode() {
        return mode_;
    }

    /**
     * <code>optional int32 mode = 3;</code>
     *
     * @param value The mode to set.
     */
    private void setMode(int value) {
        bitField0_ |= 0x00000004;
        mode_ = value;
    }

    /**
     * <code>optional int32 mode = 3;</code>
     */
    private void clearMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mode_ = 0;
    }

    public static final int FONTSIZE_FIELD_NUMBER = 4;
    private int fontSize_;

    /**
     * <code>optional int32 fontSize = 4;</code>
     *
     * @return Whether the fontSize field is set.
     */
    @Override
    public boolean hasFontSize() {
        return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <code>optional int32 fontSize = 4;</code>
     *
     * @return The fontSize.
     */
    @Override
    public int getFontSize() {
        return fontSize_;
    }

    /**
     * <code>optional int32 fontSize = 4;</code>
     *
     * @param value The fontSize to set.
     */
    private void setFontSize(int value) {
        bitField0_ |= 0x00000008;
        fontSize_ = value;
    }

    /**
     * <code>optional int32 fontSize = 4;</code>
     */
    private void clearFontSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fontSize_ = 0;
    }

    public static final int COLOR_FIELD_NUMBER = 5;
    private int color_;

    /**
     * <code>optional uint32 color = 5;</code>
     *
     * @return Whether the color field is set.
     */
    @Override
    public boolean hasColor() {
        return ((bitField0_ & 0x00000010) != 0);
    }

    /**
     * <code>optional uint32 color = 5;</code>
     *
     * @return The color.
     */
    @Override
    public int getColor() {
        return color_;
    }

    /**
     * <code>optional uint32 color = 5;</code>
     *
     * @param value The color to set.
     */
    private void setColor(int value) {
        bitField0_ |= 0x00000010;
        color_ = value;
    }

    /**
     * <code>optional uint32 color = 5;</code>
     */
    private void clearColor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        color_ = 0;
    }

    public static final int MIDHASH_FIELD_NUMBER = 6;
    private String midHash_;

    /**
     * <code>optional string midHash = 6;</code>
     *
     * @return Whether the midHash field is set.
     */
    @Override
    public boolean hasMidHash() {
        return ((bitField0_ & 0x00000020) != 0);
    }

    /**
     * <code>optional string midHash = 6;</code>
     *
     * @return The midHash.
     */
    @Override
    public String getMidHash() {
        return midHash_;
    }

    /**
     * <code>optional string midHash = 6;</code>
     *
     * @return The bytes for midHash.
     */
    @Override
    public com.google.protobuf.ByteString
    getMidHashBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(midHash_);
    }

    /**
     * <code>optional string midHash = 6;</code>
     *
     * @param value The midHash to set.
     */
    private void setMidHash(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000020;
        midHash_ = value;
    }

    /**
     * <code>optional string midHash = 6;</code>
     */
    private void clearMidHash() {
        bitField0_ = (bitField0_ & ~0x00000020);
        midHash_ = getDefaultInstance().getMidHash();
    }

    /**
     * <code>optional string midHash = 6;</code>
     *
     * @param value The bytes for midHash to set.
     */
    private void setMidHashBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        midHash_ = value.toStringUtf8();
        bitField0_ |= 0x00000020;
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private String content_;

    /**
     * <code>optional string content = 7;</code>
     *
     * @return Whether the content field is set.
     */
    @Override
    public boolean hasContent() {
        return ((bitField0_ & 0x00000040) != 0);
    }

    /**
     * <code>optional string content = 7;</code>
     *
     * @return The content.
     */
    @Override
    public String getContent() {
        return content_;
    }

    /**
     * <code>optional string content = 7;</code>
     *
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
    getContentBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(content_);
    }

    /**
     * <code>optional string content = 7;</code>
     *
     * @param value The content to set.
     */
    private void setContent(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000040;
        content_ = value;
    }

    /**
     * <code>optional string content = 7;</code>
     */
    private void clearContent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        content_ = getDefaultInstance().getContent();
    }

    /**
     * <code>optional string content = 7;</code>
     *
     * @param value The bytes for content to set.
     */
    private void setContentBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        content_ = value.toStringUtf8();
        bitField0_ |= 0x00000040;
    }

    public static final int CTIME_FIELD_NUMBER = 8;
    private long ctime_;

    /**
     * <code>optional int64 ctime = 8;</code>
     *
     * @return Whether the ctime field is set.
     */
    @Override
    public boolean hasCtime() {
        return ((bitField0_ & 0x00000080) != 0);
    }

    /**
     * <code>optional int64 ctime = 8;</code>
     *
     * @return The ctime.
     */
    @Override
    public long getCtime() {
        return ctime_;
    }

    /**
     * <code>optional int64 ctime = 8;</code>
     *
     * @param value The ctime to set.
     */
    private void setCtime(long value) {
        bitField0_ |= 0x00000080;
        ctime_ = value;
    }

    /**
     * <code>optional int64 ctime = 8;</code>
     */
    private void clearCtime() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ctime_ = 0L;
    }

    public static final int WEIGHT_FIELD_NUMBER = 9;
    private int weight_;

    /**
     * <code>optional int32 weight = 9;</code>
     *
     * @return Whether the weight field is set.
     */
    @Override
    public boolean hasWeight() {
        return ((bitField0_ & 0x00000100) != 0);
    }

    /**
     * <code>optional int32 weight = 9;</code>
     *
     * @return The weight.
     */
    @Override
    public int getWeight() {
        return weight_;
    }

    /**
     * <code>optional int32 weight = 9;</code>
     *
     * @param value The weight to set.
     */
    private void setWeight(int value) {
        bitField0_ |= 0x00000100;
        weight_ = value;
    }

    /**
     * <code>optional int32 weight = 9;</code>
     */
    private void clearWeight() {
        bitField0_ = (bitField0_ & ~0x00000100);
        weight_ = 0;
    }

    public static final int ACTION_FIELD_NUMBER = 10;
    private String action_;

    /**
     * <code>optional string action = 10;</code>
     *
     * @return Whether the action field is set.
     */
    @Override
    public boolean hasAction() {
        return ((bitField0_ & 0x00000200) != 0);
    }

    /**
     * <code>optional string action = 10;</code>
     *
     * @return The action.
     */
    @Override
    public String getAction() {
        return action_;
    }

    /**
     * <code>optional string action = 10;</code>
     *
     * @return The bytes for action.
     */
    @Override
    public com.google.protobuf.ByteString
    getActionBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(action_);
    }

    /**
     * <code>optional string action = 10;</code>
     *
     * @param value The action to set.
     */
    private void setAction(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000200;
        action_ = value;
    }

    /**
     * <code>optional string action = 10;</code>
     */
    private void clearAction() {
        bitField0_ = (bitField0_ & ~0x00000200);
        action_ = getDefaultInstance().getAction();
    }

    /**
     * <code>optional string action = 10;</code>
     *
     * @param value The bytes for action to set.
     */
    private void setActionBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        action_ = value.toStringUtf8();
        bitField0_ |= 0x00000200;
    }

    public static final int POOL_FIELD_NUMBER = 11;
    private int pool_;

    /**
     * <code>optional int32 pool = 11;</code>
     *
     * @return Whether the pool field is set.
     */
    @Override
    public boolean hasPool() {
        return ((bitField0_ & 0x00000400) != 0);
    }

    /**
     * <code>optional int32 pool = 11;</code>
     *
     * @return The pool.
     */
    @Override
    public int getPool() {
        return pool_;
    }

    /**
     * <code>optional int32 pool = 11;</code>
     *
     * @param value The pool to set.
     */
    private void setPool(int value) {
        bitField0_ |= 0x00000400;
        pool_ = value;
    }

    /**
     * <code>optional int32 pool = 11;</code>
     */
    private void clearPool() {
        bitField0_ = (bitField0_ & ~0x00000400);
        pool_ = 0;
    }

    public static final int IDSTR_FIELD_NUMBER = 12;
    private String idStr_;

    /**
     * <code>optional string idStr = 12;</code>
     *
     * @return Whether the idStr field is set.
     */
    @Override
    public boolean hasIdStr() {
        return ((bitField0_ & 0x00000800) != 0);
    }

    /**
     * <code>optional string idStr = 12;</code>
     *
     * @return The idStr.
     */
    @Override
    public String getIdStr() {
        return idStr_;
    }

    /**
     * <code>optional string idStr = 12;</code>
     *
     * @return The bytes for idStr.
     */
    @Override
    public com.google.protobuf.ByteString
    getIdStrBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(idStr_);
    }

    /**
     * <code>optional string idStr = 12;</code>
     *
     * @param value The idStr to set.
     */
    private void setIdStr(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000800;
        idStr_ = value;
    }

    /**
     * <code>optional string idStr = 12;</code>
     */
    private void clearIdStr() {
        bitField0_ = (bitField0_ & ~0x00000800);
        idStr_ = getDefaultInstance().getIdStr();
    }

    /**
     * <code>optional string idStr = 12;</code>
     *
     * @param value The bytes for idStr to set.
     */
    private void setIdStrBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        idStr_ = value.toStringUtf8();
        bitField0_ |= 0x00000800;
    }

    public static final int ATTR_FIELD_NUMBER = 13;
    private int attr_;

    /**
     * <code>optional int32 attr = 13;</code>
     *
     * @return Whether the attr field is set.
     */
    @Override
    public boolean hasAttr() {
        return ((bitField0_ & 0x00001000) != 0);
    }

    /**
     * <code>optional int32 attr = 13;</code>
     *
     * @return The attr.
     */
    @Override
    public int getAttr() {
        return attr_;
    }

    /**
     * <code>optional int32 attr = 13;</code>
     *
     * @param value The attr to set.
     */
    private void setAttr(int value) {
        bitField0_ |= 0x00001000;
        attr_ = value;
    }

    /**
     * <code>optional int32 attr = 13;</code>
     */
    private void clearAttr() {
        bitField0_ = (bitField0_ & ~0x00001000);
        attr_ = 0;
    }

    public static final int ANIMATION_FIELD_NUMBER = 22;
    private String animation_;

    /**
     * <code>optional string animation = 22;</code>
     *
     * @return Whether the animation field is set.
     */
    @Override
    public boolean hasAnimation() {
        return ((bitField0_ & 0x00002000) != 0);
    }

    /**
     * <code>optional string animation = 22;</code>
     *
     * @return The animation.
     */
    @Override
    public String getAnimation() {
        return animation_;
    }

    /**
     * <code>optional string animation = 22;</code>
     *
     * @return The bytes for animation.
     */
    @Override
    public com.google.protobuf.ByteString
    getAnimationBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(animation_);
    }

    /**
     * <code>optional string animation = 22;</code>
     *
     * @param value The animation to set.
     */
    private void setAnimation(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00002000;
        animation_ = value;
    }

    /**
     * <code>optional string animation = 22;</code>
     */
    private void clearAnimation() {
        bitField0_ = (bitField0_ & ~0x00002000);
        animation_ = getDefaultInstance().getAnimation();
    }

    /**
     * <code>optional string animation = 22;</code>
     *
     * @param value The bytes for animation to set.
     */
    private void setAnimationBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        animation_ = value.toStringUtf8();
        bitField0_ |= 0x00002000;
    }

    public static DanmakuElem parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static DanmakuElem parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static DanmakuElem parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static DanmakuElem parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static DanmakuElem parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static DanmakuElem parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static DanmakuElem parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static DanmakuElem parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static DanmakuElem parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static DanmakuElem parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static DanmakuElem parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static DanmakuElem parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(DanmakuElem prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.DanmakuElem}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    DanmakuElem, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.DanmakuElem)
            DanmakuElemOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.DanmakuElem.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional int64 id = 1;</code>
         *
         * @return Whether the id field is set.
         */
        @Override
        public boolean hasId() {
            return instance.hasId();
        }

        /**
         * <code>optional int64 id = 1;</code>
         *
         * @return The id.
         */
        @Override
        public long getId() {
            return instance.getId();
        }

        /**
         * <code>optional int64 id = 1;</code>
         *
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(long value) {
            copyOnWrite();
            instance.setId(value);
            return this;
        }

        /**
         * <code>optional int64 id = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearId() {
            copyOnWrite();
            instance.clearId();
            return this;
        }

        /**
         * <code>optional int32 progress = 2;</code>
         *
         * @return Whether the progress field is set.
         */
        @Override
        public boolean hasProgress() {
            return instance.hasProgress();
        }

        /**
         * <code>optional int32 progress = 2;</code>
         *
         * @return The progress.
         */
        @Override
        public int getProgress() {
            return instance.getProgress();
        }

        /**
         * <code>optional int32 progress = 2;</code>
         *
         * @param value The progress to set.
         * @return This builder for chaining.
         */
        public Builder setProgress(int value) {
            copyOnWrite();
            instance.setProgress(value);
            return this;
        }

        /**
         * <code>optional int32 progress = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearProgress() {
            copyOnWrite();
            instance.clearProgress();
            return this;
        }

        /**
         * <code>optional int32 mode = 3;</code>
         *
         * @return Whether the mode field is set.
         */
        @Override
        public boolean hasMode() {
            return instance.hasMode();
        }

        /**
         * <code>optional int32 mode = 3;</code>
         *
         * @return The mode.
         */
        @Override
        public int getMode() {
            return instance.getMode();
        }

        /**
         * <code>optional int32 mode = 3;</code>
         *
         * @param value The mode to set.
         * @return This builder for chaining.
         */
        public Builder setMode(int value) {
            copyOnWrite();
            instance.setMode(value);
            return this;
        }

        /**
         * <code>optional int32 mode = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMode() {
            copyOnWrite();
            instance.clearMode();
            return this;
        }

        /**
         * <code>optional int32 fontSize = 4;</code>
         *
         * @return Whether the fontSize field is set.
         */
        @Override
        public boolean hasFontSize() {
            return instance.hasFontSize();
        }

        /**
         * <code>optional int32 fontSize = 4;</code>
         *
         * @return The fontSize.
         */
        @Override
        public int getFontSize() {
            return instance.getFontSize();
        }

        /**
         * <code>optional int32 fontSize = 4;</code>
         *
         * @param value The fontSize to set.
         * @return This builder for chaining.
         */
        public Builder setFontSize(int value) {
            copyOnWrite();
            instance.setFontSize(value);
            return this;
        }

        /**
         * <code>optional int32 fontSize = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearFontSize() {
            copyOnWrite();
            instance.clearFontSize();
            return this;
        }

        /**
         * <code>optional uint32 color = 5;</code>
         *
         * @return Whether the color field is set.
         */
        @Override
        public boolean hasColor() {
            return instance.hasColor();
        }

        /**
         * <code>optional uint32 color = 5;</code>
         *
         * @return The color.
         */
        @Override
        public int getColor() {
            return instance.getColor();
        }

        /**
         * <code>optional uint32 color = 5;</code>
         *
         * @param value The color to set.
         * @return This builder for chaining.
         */
        public Builder setColor(int value) {
            copyOnWrite();
            instance.setColor(value);
            return this;
        }

        /**
         * <code>optional uint32 color = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearColor() {
            copyOnWrite();
            instance.clearColor();
            return this;
        }

        /**
         * <code>optional string midHash = 6;</code>
         *
         * @return Whether the midHash field is set.
         */
        @Override
        public boolean hasMidHash() {
            return instance.hasMidHash();
        }

        /**
         * <code>optional string midHash = 6;</code>
         *
         * @return The midHash.
         */
        @Override
        public String getMidHash() {
            return instance.getMidHash();
        }

        /**
         * <code>optional string midHash = 6;</code>
         *
         * @return The bytes for midHash.
         */
        @Override
        public com.google.protobuf.ByteString
        getMidHashBytes() {
            return instance.getMidHashBytes();
        }

        /**
         * <code>optional string midHash = 6;</code>
         *
         * @param value The midHash to set.
         * @return This builder for chaining.
         */
        public Builder setMidHash(
                String value) {
            copyOnWrite();
            instance.setMidHash(value);
            return this;
        }

        /**
         * <code>optional string midHash = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMidHash() {
            copyOnWrite();
            instance.clearMidHash();
            return this;
        }

        /**
         * <code>optional string midHash = 6;</code>
         *
         * @param value The bytes for midHash to set.
         * @return This builder for chaining.
         */
        public Builder setMidHashBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setMidHashBytes(value);
            return this;
        }

        /**
         * <code>optional string content = 7;</code>
         *
         * @return Whether the content field is set.
         */
        @Override
        public boolean hasContent() {
            return instance.hasContent();
        }

        /**
         * <code>optional string content = 7;</code>
         *
         * @return The content.
         */
        @Override
        public String getContent() {
            return instance.getContent();
        }

        /**
         * <code>optional string content = 7;</code>
         *
         * @return The bytes for content.
         */
        @Override
        public com.google.protobuf.ByteString
        getContentBytes() {
            return instance.getContentBytes();
        }

        /**
         * <code>optional string content = 7;</code>
         *
         * @param value The content to set.
         * @return This builder for chaining.
         */
        public Builder setContent(
                String value) {
            copyOnWrite();
            instance.setContent(value);
            return this;
        }

        /**
         * <code>optional string content = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearContent() {
            copyOnWrite();
            instance.clearContent();
            return this;
        }

        /**
         * <code>optional string content = 7;</code>
         *
         * @param value The bytes for content to set.
         * @return This builder for chaining.
         */
        public Builder setContentBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setContentBytes(value);
            return this;
        }

        /**
         * <code>optional int64 ctime = 8;</code>
         *
         * @return Whether the ctime field is set.
         */
        @Override
        public boolean hasCtime() {
            return instance.hasCtime();
        }

        /**
         * <code>optional int64 ctime = 8;</code>
         *
         * @return The ctime.
         */
        @Override
        public long getCtime() {
            return instance.getCtime();
        }

        /**
         * <code>optional int64 ctime = 8;</code>
         *
         * @param value The ctime to set.
         * @return This builder for chaining.
         */
        public Builder setCtime(long value) {
            copyOnWrite();
            instance.setCtime(value);
            return this;
        }

        /**
         * <code>optional int64 ctime = 8;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCtime() {
            copyOnWrite();
            instance.clearCtime();
            return this;
        }

        /**
         * <code>optional int32 weight = 9;</code>
         *
         * @return Whether the weight field is set.
         */
        @Override
        public boolean hasWeight() {
            return instance.hasWeight();
        }

        /**
         * <code>optional int32 weight = 9;</code>
         *
         * @return The weight.
         */
        @Override
        public int getWeight() {
            return instance.getWeight();
        }

        /**
         * <code>optional int32 weight = 9;</code>
         *
         * @param value The weight to set.
         * @return This builder for chaining.
         */
        public Builder setWeight(int value) {
            copyOnWrite();
            instance.setWeight(value);
            return this;
        }

        /**
         * <code>optional int32 weight = 9;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearWeight() {
            copyOnWrite();
            instance.clearWeight();
            return this;
        }

        /**
         * <code>optional string action = 10;</code>
         *
         * @return Whether the action field is set.
         */
        @Override
        public boolean hasAction() {
            return instance.hasAction();
        }

        /**
         * <code>optional string action = 10;</code>
         *
         * @return The action.
         */
        @Override
        public String getAction() {
            return instance.getAction();
        }

        /**
         * <code>optional string action = 10;</code>
         *
         * @return The bytes for action.
         */
        @Override
        public com.google.protobuf.ByteString
        getActionBytes() {
            return instance.getActionBytes();
        }

        /**
         * <code>optional string action = 10;</code>
         *
         * @param value The action to set.
         * @return This builder for chaining.
         */
        public Builder setAction(
                String value) {
            copyOnWrite();
            instance.setAction(value);
            return this;
        }

        /**
         * <code>optional string action = 10;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAction() {
            copyOnWrite();
            instance.clearAction();
            return this;
        }

        /**
         * <code>optional string action = 10;</code>
         *
         * @param value The bytes for action to set.
         * @return This builder for chaining.
         */
        public Builder setActionBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setActionBytes(value);
            return this;
        }

        /**
         * <code>optional int32 pool = 11;</code>
         *
         * @return Whether the pool field is set.
         */
        @Override
        public boolean hasPool() {
            return instance.hasPool();
        }

        /**
         * <code>optional int32 pool = 11;</code>
         *
         * @return The pool.
         */
        @Override
        public int getPool() {
            return instance.getPool();
        }

        /**
         * <code>optional int32 pool = 11;</code>
         *
         * @param value The pool to set.
         * @return This builder for chaining.
         */
        public Builder setPool(int value) {
            copyOnWrite();
            instance.setPool(value);
            return this;
        }

        /**
         * <code>optional int32 pool = 11;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPool() {
            copyOnWrite();
            instance.clearPool();
            return this;
        }

        /**
         * <code>optional string idStr = 12;</code>
         *
         * @return Whether the idStr field is set.
         */
        @Override
        public boolean hasIdStr() {
            return instance.hasIdStr();
        }

        /**
         * <code>optional string idStr = 12;</code>
         *
         * @return The idStr.
         */
        @Override
        public String getIdStr() {
            return instance.getIdStr();
        }

        /**
         * <code>optional string idStr = 12;</code>
         *
         * @return The bytes for idStr.
         */
        @Override
        public com.google.protobuf.ByteString
        getIdStrBytes() {
            return instance.getIdStrBytes();
        }

        /**
         * <code>optional string idStr = 12;</code>
         *
         * @param value The idStr to set.
         * @return This builder for chaining.
         */
        public Builder setIdStr(
                String value) {
            copyOnWrite();
            instance.setIdStr(value);
            return this;
        }

        /**
         * <code>optional string idStr = 12;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIdStr() {
            copyOnWrite();
            instance.clearIdStr();
            return this;
        }

        /**
         * <code>optional string idStr = 12;</code>
         *
         * @param value The bytes for idStr to set.
         * @return This builder for chaining.
         */
        public Builder setIdStrBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setIdStrBytes(value);
            return this;
        }

        /**
         * <code>optional int32 attr = 13;</code>
         *
         * @return Whether the attr field is set.
         */
        @Override
        public boolean hasAttr() {
            return instance.hasAttr();
        }

        /**
         * <code>optional int32 attr = 13;</code>
         *
         * @return The attr.
         */
        @Override
        public int getAttr() {
            return instance.getAttr();
        }

        /**
         * <code>optional int32 attr = 13;</code>
         *
         * @param value The attr to set.
         * @return This builder for chaining.
         */
        public Builder setAttr(int value) {
            copyOnWrite();
            instance.setAttr(value);
            return this;
        }

        /**
         * <code>optional int32 attr = 13;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAttr() {
            copyOnWrite();
            instance.clearAttr();
            return this;
        }

        /**
         * <code>optional string animation = 22;</code>
         *
         * @return Whether the animation field is set.
         */
        @Override
        public boolean hasAnimation() {
            return instance.hasAnimation();
        }

        /**
         * <code>optional string animation = 22;</code>
         *
         * @return The animation.
         */
        @Override
        public String getAnimation() {
            return instance.getAnimation();
        }

        /**
         * <code>optional string animation = 22;</code>
         *
         * @return The bytes for animation.
         */
        @Override
        public com.google.protobuf.ByteString
        getAnimationBytes() {
            return instance.getAnimationBytes();
        }

        /**
         * <code>optional string animation = 22;</code>
         *
         * @param value The animation to set.
         * @return This builder for chaining.
         */
        public Builder setAnimation(
                String value) {
            copyOnWrite();
            instance.setAnimation(value);
            return this;
        }

        /**
         * <code>optional string animation = 22;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAnimation() {
            copyOnWrite();
            instance.clearAnimation();
            return this;
        }

        /**
         * <code>optional string animation = 22;</code>
         *
         * @param value The bytes for animation to set.
         * @return This builder for chaining.
         */
        public Builder setAnimationBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setAnimationBytes(value);
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.DanmakuElem)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new DanmakuElem();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "id_",
                        "progress_",
                        "mode_",
                        "fontSize_",
                        "color_",
                        "midHash_",
                        "content_",
                        "ctime_",
                        "weight_",
                        "action_",
                        "pool_",
                        "idStr_",
                        "attr_",
                        "animation_",
                };
                String info =
                        "\u0000\u000e\u0000\u0001\u0001\u0016\u000e\u0000\u0000\u0000\u0001\u1002\u0000\u0002" +
                                "\u1004\u0001\u0003\u1004\u0002\u0004\u1004\u0003\u0005\u100b\u0004\u0006\u1208\u0005" +
                                "\u0007\u1208\u0006\b\u1002\u0007\t\u1004\b\n\u1208\t\u000b\u1004\n\f\u1208\u000b" +
                                "\r\u1004\f\u0016\u1208\r";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<DanmakuElem> parser = PARSER;
                if (parser == null) {
                    synchronized (DanmakuElem.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<DanmakuElem>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.DanmakuElem)
    private static final DanmakuElem DEFAULT_INSTANCE;

    static {
        DanmakuElem defaultInstance = new DanmakuElem();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                DanmakuElem.class, defaultInstance);
    }

    public static DanmakuElem getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DanmakuElem> PARSER;

    public static com.google.protobuf.Parser<DanmakuElem> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

