// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface DanmakuFlagConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 recFlag = 1;</code>
     *
     * @return Whether the recFlag field is set.
     */
    boolean hasRecFlag();

    /**
     * <code>optional int32 recFlag = 1;</code>
     *
     * @return The recFlag.
     */
    int getRecFlag();

    /**
     * <code>optional string recText = 2;</code>
     *
     * @return Whether the recText field is set.
     */
    boolean hasRecText();

    /**
     * <code>optional string recText = 2;</code>
     *
     * @return The recText.
     */
    String getRecText();

    /**
     * <code>optional string recText = 2;</code>
     *
     * @return The bytes for recText.
     */
    com.google.protobuf.ByteString
    getRecTextBytes();

    /**
     * <code>optional int32 recSwitch = 3;</code>
     *
     * @return Whether the recSwitch field is set.
     */
    boolean hasRecSwitch();

    /**
     * <code>optional int32 recSwitch = 3;</code>
     *
     * @return The recSwitch.
     */
    int getRecSwitch();
}
