// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface DmSegConfigOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.DmSegConfig)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 pageSize = 1;</code>
     *
     * @return Whether the pageSize field is set.
     */
    boolean hasPageSize();

    /**
     * <code>optional int64 pageSize = 1;</code>
     *
     * @return The pageSize.
     */
    long getPageSize();

    /**
     * <code>optional int64 total = 2;</code>
     *
     * @return Whether the total field is set.
     */
    boolean hasTotal();

    /**
     * <code>optional int64 total = 2;</code>
     *
     * @return The total.
     */
    long getTotal();
}
