// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface DmSegMobileReplyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.DmSegMobileReply)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.DanmakuElem elems = 1;</code>
     */
    java.util.List<DanmakuElem>
    getElemsList();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.DanmakuElem elems = 1;</code>
     */
    DanmakuElem getElems(int index);

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.DanmakuElem elems = 1;</code>
     */
    int getElemsCount();
}
