// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface DmWebViewReplyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.DmWebViewReply)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int32 state = 1;</code>
     *
     * @return Whether the state field is set.
     */
    boolean hasState();

    /**
     * <code>optional int32 state = 1;</code>
     *
     * @return The state.
     */
    int getState();

    /**
     * <code>optional string text = 2;</code>
     *
     * @return Whether the text field is set.
     */
    boolean hasText();

    /**
     * <code>optional string text = 2;</code>
     *
     * @return The text.
     */
    String getText();

    /**
     * <code>optional string text = 2;</code>
     *
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
    getTextBytes();

    /**
     * <code>optional string textSide = 3;</code>
     *
     * @return Whether the textSide field is set.
     */
    boolean hasTextSide();

    /**
     * <code>optional string textSide = 3;</code>
     *
     * @return The textSide.
     */
    String getTextSide();

    /**
     * <code>optional string textSide = 3;</code>
     *
     * @return The bytes for textSide.
     */
    com.google.protobuf.ByteString
    getTextSideBytes();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
     *
     * @return Whether the dmSge field is set.
     */
    boolean hasDmSge();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
     *
     * @return The dmSge.
     */
    DmSegConfig getDmSge();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
     *
     * @return Whether the flag field is set.
     */
    boolean hasFlag();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
     *
     * @return The flag.
     */
    DanmakuFlagConfig getFlag();

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @return A list containing the specialDms.
     */
    java.util.List<String>
    getSpecialDmsList();

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @return The count of specialDms.
     */
    int getSpecialDmsCount();

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @param index The index of the element to return.
     * @return The specialDms at the given index.
     */
    String getSpecialDms(int index);

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @param index The index of the element to return.
     * @return The specialDms at the given index.
     */
    com.google.protobuf.ByteString
    getSpecialDmsBytes(int index);

    /**
     * <code>optional bool checkBox = 7;</code>
     *
     * @return Whether the checkBox field is set.
     */
    boolean hasCheckBox();

    /**
     * <code>optional bool checkBox = 7;</code>
     *
     * @return The checkBox.
     */
    boolean getCheckBox();

    /**
     * <code>optional int64 count = 8;</code>
     *
     * @return Whether the count field is set.
     */
    boolean hasCount();

    /**
     * <code>optional int64 count = 8;</code>
     *
     * @return The count.
     */
    long getCount();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    java.util.List<CommandDm>
    getCommandDmsList();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    CommandDm getCommandDms(int index);

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    int getCommandDmsCount();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
     *
     * @return Whether the dmSetting field is set.
     */
    boolean hasDmSetting();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
     *
     * @return The dmSetting.
     */
    DanmuWebPlayerConfig getDmSetting();

    /**
     * <code>optional string reportFilter = 11;</code>
     *
     * @return Whether the reportFilter field is set.
     */
    boolean hasReportFilter();

    /**
     * <code>optional string reportFilter = 11;</code>
     *
     * @return The reportFilter.
     */
    String getReportFilter();

    /**
     * <code>optional string reportFilter = 11;</code>
     *
     * @return The bytes for reportFilter.
     */
    com.google.protobuf.ByteString
    getReportFilterBytes();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    java.util.List<Expressions>
    getExpressionsList();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    Expressions getExpressions(int index);

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    int getExpressionsCount();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    java.util.List<PostPanel>
    getPostPanelList();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    PostPanel getPostPanel(int index);

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    int getPostPanelCount();
}
