// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.DmWebViewReply}
 */
public final class DmWebViewReply extends
        com.google.protobuf.GeneratedMessageLite<
                DmWebViewReply, DmWebViewReply.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.DmWebViewReply)
        DmWebViewReplyOrBuilder {
    private DmWebViewReply() {
        text_ = "";
        textSide_ = "";
        specialDms_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        commandDms_ = emptyProtobufList();
        reportFilter_ = "";
        expressions_ = emptyProtobufList();
        postPanel_ = emptyProtobufList();
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;

    /**
     * <code>optional int32 state = 1;</code>
     *
     * @return Whether the state field is set.
     */
    @Override
    public boolean hasState() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional int32 state = 1;</code>
     *
     * @return The state.
     */
    @Override
    public int getState() {
        return state_;
    }

    /**
     * <code>optional int32 state = 1;</code>
     *
     * @param value The state to set.
     */
    private void setState(int value) {
        bitField0_ |= 0x00000001;
        state_ = value;
    }

    /**
     * <code>optional int32 state = 1;</code>
     */
    private void clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private String text_;

    /**
     * <code>optional string text = 2;</code>
     *
     * @return Whether the text field is set.
     */
    @Override
    public boolean hasText() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional string text = 2;</code>
     *
     * @return The text.
     */
    @Override
    public String getText() {
        return text_;
    }

    /**
     * <code>optional string text = 2;</code>
     *
     * @return The bytes for text.
     */
    @Override
    public com.google.protobuf.ByteString
    getTextBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(text_);
    }

    /**
     * <code>optional string text = 2;</code>
     *
     * @param value The text to set.
     */
    private void setText(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000002;
        text_ = value;
    }

    /**
     * <code>optional string text = 2;</code>
     */
    private void clearText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = getDefaultInstance().getText();
    }

    /**
     * <code>optional string text = 2;</code>
     *
     * @param value The bytes for text to set.
     */
    private void setTextBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        text_ = value.toStringUtf8();
        bitField0_ |= 0x00000002;
    }

    public static final int TEXTSIDE_FIELD_NUMBER = 3;
    private String textSide_;

    /**
     * <code>optional string textSide = 3;</code>
     *
     * @return Whether the textSide field is set.
     */
    @Override
    public boolean hasTextSide() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>optional string textSide = 3;</code>
     *
     * @return The textSide.
     */
    @Override
    public String getTextSide() {
        return textSide_;
    }

    /**
     * <code>optional string textSide = 3;</code>
     *
     * @return The bytes for textSide.
     */
    @Override
    public com.google.protobuf.ByteString
    getTextSideBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(textSide_);
    }

    /**
     * <code>optional string textSide = 3;</code>
     *
     * @param value The textSide to set.
     */
    private void setTextSide(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000004;
        textSide_ = value;
    }

    /**
     * <code>optional string textSide = 3;</code>
     */
    private void clearTextSide() {
        bitField0_ = (bitField0_ & ~0x00000004);
        textSide_ = getDefaultInstance().getTextSide();
    }

    /**
     * <code>optional string textSide = 3;</code>
     *
     * @param value The bytes for textSide to set.
     */
    private void setTextSideBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        textSide_ = value.toStringUtf8();
        bitField0_ |= 0x00000004;
    }

    public static final int DMSGE_FIELD_NUMBER = 4;
    private DmSegConfig dmSge_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
     */
    @Override
    public boolean hasDmSge() {
        return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
     */
    @Override
    public DmSegConfig getDmSge() {
        return dmSge_ == null ? DmSegConfig.getDefaultInstance() : dmSge_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
     */
    private void setDmSge(DmSegConfig value) {
        value.getClass();
        dmSge_ = value;
        bitField0_ |= 0x00000008;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeDmSge(DmSegConfig value) {
        value.getClass();
        if (dmSge_ != null &&
                dmSge_ != DmSegConfig.getDefaultInstance()) {
            dmSge_ =
                    DmSegConfig.newBuilder(dmSge_).mergeFrom(value).buildPartial();
        } else {
            dmSge_ = value;
        }
        bitField0_ |= 0x00000008;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
     */
    private void clearDmSge() {
        dmSge_ = null;
        bitField0_ = (bitField0_ & ~0x00000008);
    }

    public static final int FLAG_FIELD_NUMBER = 5;
    private DanmakuFlagConfig flag_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
     */
    @Override
    public boolean hasFlag() {
        return ((bitField0_ & 0x00000010) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
     */
    @Override
    public DanmakuFlagConfig getFlag() {
        return flag_ == null ? DanmakuFlagConfig.getDefaultInstance() : flag_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
     */
    private void setFlag(DanmakuFlagConfig value) {
        value.getClass();
        flag_ = value;
        bitField0_ |= 0x00000010;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeFlag(DanmakuFlagConfig value) {
        value.getClass();
        if (flag_ != null &&
                flag_ != DanmakuFlagConfig.getDefaultInstance()) {
            flag_ =
                    DanmakuFlagConfig.newBuilder(flag_).mergeFrom(value).buildPartial();
        } else {
            flag_ = value;
        }
        bitField0_ |= 0x00000010;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
     */
    private void clearFlag() {
        flag_ = null;
        bitField0_ = (bitField0_ & ~0x00000010);
    }

    public static final int SPECIALDMS_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.ProtobufList<String> specialDms_;

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @return A list containing the specialDms.
     */
    @Override
    public java.util.List<String> getSpecialDmsList() {
        return specialDms_;
    }

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @return The count of specialDms.
     */
    @Override
    public int getSpecialDmsCount() {
        return specialDms_.size();
    }

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @param index The index of the element to return.
     * @return The specialDms at the given index.
     */
    @Override
    public String getSpecialDms(int index) {
        return specialDms_.get(index);
    }

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the specialDms at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
    getSpecialDmsBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
                specialDms_.get(index));
    }

    private void ensureSpecialDmsIsMutable() {
        com.google.protobuf.Internal.ProtobufList<String> tmp =
                specialDms_;
        if (!tmp.isModifiable()) {
            specialDms_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @param index The index to set the value at.
     * @param value The specialDms to set.
     */
    private void setSpecialDms(
            int index, String value) {
        Class<?> valueClass = value.getClass();
        ensureSpecialDmsIsMutable();
        specialDms_.set(index, value);
    }

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @param value The specialDms to add.
     */
    private void addSpecialDms(
            String value) {
        Class<?> valueClass = value.getClass();
        ensureSpecialDmsIsMutable();
        specialDms_.add(value);
    }

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @param values The specialDms to add.
     */
    private void addAllSpecialDms(
            Iterable<String> values) {
        ensureSpecialDmsIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, specialDms_);
    }

    /**
     * <code>repeated string specialDms = 6;</code>
     */
    private void clearSpecialDms() {
        specialDms_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    /**
     * <code>repeated string specialDms = 6;</code>
     *
     * @param value The bytes of the specialDms to add.
     */
    private void addSpecialDmsBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensureSpecialDmsIsMutable();
        specialDms_.add(value.toStringUtf8());
    }

    public static final int CHECKBOX_FIELD_NUMBER = 7;
    private boolean checkBox_;

    /**
     * <code>optional bool checkBox = 7;</code>
     *
     * @return Whether the checkBox field is set.
     */
    @Override
    public boolean hasCheckBox() {
        return ((bitField0_ & 0x00000020) != 0);
    }

    /**
     * <code>optional bool checkBox = 7;</code>
     *
     * @return The checkBox.
     */
    @Override
    public boolean getCheckBox() {
        return checkBox_;
    }

    /**
     * <code>optional bool checkBox = 7;</code>
     *
     * @param value The checkBox to set.
     */
    private void setCheckBox(boolean value) {
        bitField0_ |= 0x00000020;
        checkBox_ = value;
    }

    /**
     * <code>optional bool checkBox = 7;</code>
     */
    private void clearCheckBox() {
        bitField0_ = (bitField0_ & ~0x00000020);
        checkBox_ = false;
    }

    public static final int COUNT_FIELD_NUMBER = 8;
    private long count_;

    /**
     * <code>optional int64 count = 8;</code>
     *
     * @return Whether the count field is set.
     */
    @Override
    public boolean hasCount() {
        return ((bitField0_ & 0x00000040) != 0);
    }

    /**
     * <code>optional int64 count = 8;</code>
     *
     * @return The count.
     */
    @Override
    public long getCount() {
        return count_;
    }

    /**
     * <code>optional int64 count = 8;</code>
     *
     * @param value The count to set.
     */
    private void setCount(long value) {
        bitField0_ |= 0x00000040;
        count_ = value;
    }

    /**
     * <code>optional int64 count = 8;</code>
     */
    private void clearCount() {
        bitField0_ = (bitField0_ & ~0x00000040);
        count_ = 0L;
    }

    public static final int COMMANDDMS_FIELD_NUMBER = 9;
    private com.google.protobuf.Internal.ProtobufList<CommandDm> commandDms_;

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    @Override
    public java.util.List<CommandDm> getCommandDmsList() {
        return commandDms_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    public java.util.List<? extends CommandDmOrBuilder>
    getCommandDmsOrBuilderList() {
        return commandDms_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    @Override
    public int getCommandDmsCount() {
        return commandDms_.size();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    @Override
    public CommandDm getCommandDms(int index) {
        return commandDms_.get(index);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    public CommandDmOrBuilder getCommandDmsOrBuilder(
            int index) {
        return commandDms_.get(index);
    }

    private void ensureCommandDmsIsMutable() {
        com.google.protobuf.Internal.ProtobufList<CommandDm> tmp = commandDms_;
        if (!tmp.isModifiable()) {
            commandDms_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    private void setCommandDms(
            int index, CommandDm value) {
        value.getClass();
        ensureCommandDmsIsMutable();
        commandDms_.set(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    private void addCommandDms(CommandDm value) {
        value.getClass();
        ensureCommandDmsIsMutable();
        commandDms_.add(value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    private void addCommandDms(
            int index, CommandDm value) {
        value.getClass();
        ensureCommandDmsIsMutable();
        commandDms_.add(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    private void addAllCommandDms(
            Iterable<? extends CommandDm> values) {
        ensureCommandDmsIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, commandDms_);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    private void clearCommandDms() {
        commandDms_ = emptyProtobufList();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
     */
    private void removeCommandDms(int index) {
        ensureCommandDmsIsMutable();
        commandDms_.remove(index);
    }

    public static final int DMSETTING_FIELD_NUMBER = 10;
    private DanmuWebPlayerConfig dmSetting_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
     */
    @Override
    public boolean hasDmSetting() {
        return ((bitField0_ & 0x00000080) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
     */
    @Override
    public DanmuWebPlayerConfig getDmSetting() {
        return dmSetting_ == null ? DanmuWebPlayerConfig.getDefaultInstance() : dmSetting_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
     */
    private void setDmSetting(DanmuWebPlayerConfig value) {
        value.getClass();
        dmSetting_ = value;
        bitField0_ |= 0x00000080;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeDmSetting(DanmuWebPlayerConfig value) {
        value.getClass();
        if (dmSetting_ != null &&
                dmSetting_ != DanmuWebPlayerConfig.getDefaultInstance()) {
            dmSetting_ =
                    DanmuWebPlayerConfig.newBuilder(dmSetting_).mergeFrom(value).buildPartial();
        } else {
            dmSetting_ = value;
        }
        bitField0_ |= 0x00000080;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
     */
    private void clearDmSetting() {
        dmSetting_ = null;
        bitField0_ = (bitField0_ & ~0x00000080);
    }

    public static final int REPORTFILTER_FIELD_NUMBER = 11;
    private String reportFilter_;

    /**
     * <code>optional string reportFilter = 11;</code>
     *
     * @return Whether the reportFilter field is set.
     */
    @Override
    public boolean hasReportFilter() {
        return ((bitField0_ & 0x00000100) != 0);
    }

    /**
     * <code>optional string reportFilter = 11;</code>
     *
     * @return The reportFilter.
     */
    @Override
    public String getReportFilter() {
        return reportFilter_;
    }

    /**
     * <code>optional string reportFilter = 11;</code>
     *
     * @return The bytes for reportFilter.
     */
    @Override
    public com.google.protobuf.ByteString
    getReportFilterBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(reportFilter_);
    }

    /**
     * <code>optional string reportFilter = 11;</code>
     *
     * @param value The reportFilter to set.
     */
    private void setReportFilter(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000100;
        reportFilter_ = value;
    }

    /**
     * <code>optional string reportFilter = 11;</code>
     */
    private void clearReportFilter() {
        bitField0_ = (bitField0_ & ~0x00000100);
        reportFilter_ = getDefaultInstance().getReportFilter();
    }

    /**
     * <code>optional string reportFilter = 11;</code>
     *
     * @param value The bytes for reportFilter to set.
     */
    private void setReportFilterBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        reportFilter_ = value.toStringUtf8();
        bitField0_ |= 0x00000100;
    }

    public static final int EXPRESSIONS_FIELD_NUMBER = 12;
    private com.google.protobuf.Internal.ProtobufList<Expressions> expressions_;

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    @Override
    public java.util.List<Expressions> getExpressionsList() {
        return expressions_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    public java.util.List<? extends ExpressionsOrBuilder>
    getExpressionsOrBuilderList() {
        return expressions_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    @Override
    public int getExpressionsCount() {
        return expressions_.size();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    @Override
    public Expressions getExpressions(int index) {
        return expressions_.get(index);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    public ExpressionsOrBuilder getExpressionsOrBuilder(
            int index) {
        return expressions_.get(index);
    }

    private void ensureExpressionsIsMutable() {
        com.google.protobuf.Internal.ProtobufList<Expressions> tmp = expressions_;
        if (!tmp.isModifiable()) {
            expressions_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    private void setExpressions(
            int index, Expressions value) {
        value.getClass();
        ensureExpressionsIsMutable();
        expressions_.set(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    private void addExpressions(Expressions value) {
        value.getClass();
        ensureExpressionsIsMutable();
        expressions_.add(value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    private void addExpressions(
            int index, Expressions value) {
        value.getClass();
        ensureExpressionsIsMutable();
        expressions_.add(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    private void addAllExpressions(
            Iterable<? extends Expressions> values) {
        ensureExpressionsIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, expressions_);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    private void clearExpressions() {
        expressions_ = emptyProtobufList();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
     */
    private void removeExpressions(int index) {
        ensureExpressionsIsMutable();
        expressions_.remove(index);
    }

    public static final int POSTPANEL_FIELD_NUMBER = 13;
    private com.google.protobuf.Internal.ProtobufList<PostPanel> postPanel_;

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    @Override
    public java.util.List<PostPanel> getPostPanelList() {
        return postPanel_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    public java.util.List<? extends PostPanelOrBuilder>
    getPostPanelOrBuilderList() {
        return postPanel_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    @Override
    public int getPostPanelCount() {
        return postPanel_.size();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    @Override
    public PostPanel getPostPanel(int index) {
        return postPanel_.get(index);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    public PostPanelOrBuilder getPostPanelOrBuilder(
            int index) {
        return postPanel_.get(index);
    }

    private void ensurePostPanelIsMutable() {
        com.google.protobuf.Internal.ProtobufList<PostPanel> tmp = postPanel_;
        if (!tmp.isModifiable()) {
            postPanel_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    private void setPostPanel(
            int index, PostPanel value) {
        value.getClass();
        ensurePostPanelIsMutable();
        postPanel_.set(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    private void addPostPanel(PostPanel value) {
        value.getClass();
        ensurePostPanelIsMutable();
        postPanel_.add(value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    private void addPostPanel(
            int index, PostPanel value) {
        value.getClass();
        ensurePostPanelIsMutable();
        postPanel_.add(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    private void addAllPostPanel(
            Iterable<? extends PostPanel> values) {
        ensurePostPanelIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, postPanel_);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    private void clearPostPanel() {
        postPanel_ = emptyProtobufList();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
     */
    private void removePostPanel(int index) {
        ensurePostPanelIsMutable();
        postPanel_.remove(index);
    }

    public static DmWebViewReply parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static DmWebViewReply parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static DmWebViewReply parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static DmWebViewReply parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static DmWebViewReply parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static DmWebViewReply parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static DmWebViewReply parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static DmWebViewReply parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static DmWebViewReply parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static DmWebViewReply parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static DmWebViewReply parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static DmWebViewReply parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(DmWebViewReply prototype) {
        return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.DmWebViewReply}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    DmWebViewReply, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.DmWebViewReply)
            DmWebViewReplyOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.DmWebViewReply.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional int32 state = 1;</code>
         *
         * @return Whether the state field is set.
         */
        @Override
        public boolean hasState() {
            return instance.hasState();
        }

        /**
         * <code>optional int32 state = 1;</code>
         *
         * @return The state.
         */
        @Override
        public int getState() {
            return instance.getState();
        }

        /**
         * <code>optional int32 state = 1;</code>
         *
         * @param value The state to set.
         * @return This builder for chaining.
         */
        public Builder setState(int value) {
            copyOnWrite();
            instance.setState(value);
            return this;
        }

        /**
         * <code>optional int32 state = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearState() {
            copyOnWrite();
            instance.clearState();
            return this;
        }

        /**
         * <code>optional string text = 2;</code>
         *
         * @return Whether the text field is set.
         */
        @Override
        public boolean hasText() {
            return instance.hasText();
        }

        /**
         * <code>optional string text = 2;</code>
         *
         * @return The text.
         */
        @Override
        public String getText() {
            return instance.getText();
        }

        /**
         * <code>optional string text = 2;</code>
         *
         * @return The bytes for text.
         */
        @Override
        public com.google.protobuf.ByteString
        getTextBytes() {
            return instance.getTextBytes();
        }

        /**
         * <code>optional string text = 2;</code>
         *
         * @param value The text to set.
         * @return This builder for chaining.
         */
        public Builder setText(
                String value) {
            copyOnWrite();
            instance.setText(value);
            return this;
        }

        /**
         * <code>optional string text = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearText() {
            copyOnWrite();
            instance.clearText();
            return this;
        }

        /**
         * <code>optional string text = 2;</code>
         *
         * @param value The bytes for text to set.
         * @return This builder for chaining.
         */
        public Builder setTextBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setTextBytes(value);
            return this;
        }

        /**
         * <code>optional string textSide = 3;</code>
         *
         * @return Whether the textSide field is set.
         */
        @Override
        public boolean hasTextSide() {
            return instance.hasTextSide();
        }

        /**
         * <code>optional string textSide = 3;</code>
         *
         * @return The textSide.
         */
        @Override
        public String getTextSide() {
            return instance.getTextSide();
        }

        /**
         * <code>optional string textSide = 3;</code>
         *
         * @return The bytes for textSide.
         */
        @Override
        public com.google.protobuf.ByteString
        getTextSideBytes() {
            return instance.getTextSideBytes();
        }

        /**
         * <code>optional string textSide = 3;</code>
         *
         * @param value The textSide to set.
         * @return This builder for chaining.
         */
        public Builder setTextSide(
                String value) {
            copyOnWrite();
            instance.setTextSide(value);
            return this;
        }

        /**
         * <code>optional string textSide = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTextSide() {
            copyOnWrite();
            instance.clearTextSide();
            return this;
        }

        /**
         * <code>optional string textSide = 3;</code>
         *
         * @param value The bytes for textSide to set.
         * @return This builder for chaining.
         */
        public Builder setTextSideBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setTextSideBytes(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
         */
        @Override
        public boolean hasDmSge() {
            return instance.hasDmSge();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
         */
        @Override
        public DmSegConfig getDmSge() {
            return instance.getDmSge();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
         */
        public Builder setDmSge(DmSegConfig value) {
            copyOnWrite();
            instance.setDmSge(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
         */
        public Builder setDmSge(
                DmSegConfig.Builder builderForValue) {
            copyOnWrite();
            instance.setDmSge(builderForValue.build());
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
         */
        public Builder mergeDmSge(DmSegConfig value) {
            copyOnWrite();
            instance.mergeDmSge(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DmSegConfig dmSge = 4;</code>
         */
        public Builder clearDmSge() {
            copyOnWrite();
            instance.clearDmSge();
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
         */
        @Override
        public boolean hasFlag() {
            return instance.hasFlag();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
         */
        @Override
        public DanmakuFlagConfig getFlag() {
            return instance.getFlag();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
         */
        public Builder setFlag(DanmakuFlagConfig value) {
            copyOnWrite();
            instance.setFlag(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
         */
        public Builder setFlag(
                DanmakuFlagConfig.Builder builderForValue) {
            copyOnWrite();
            instance.setFlag(builderForValue.build());
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
         */
        public Builder mergeFlag(DanmakuFlagConfig value) {
            copyOnWrite();
            instance.mergeFlag(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmakuFlagConfig flag = 5;</code>
         */
        public Builder clearFlag() {
            copyOnWrite();
            instance.clearFlag();
            return this;
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @return A list containing the specialDms.
         */
        @Override
        public java.util.List<String>
        getSpecialDmsList() {
            return java.util.Collections.unmodifiableList(
                    instance.getSpecialDmsList());
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @return The count of specialDms.
         */
        @Override
        public int getSpecialDmsCount() {
            return instance.getSpecialDmsCount();
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @param index The index of the element to return.
         * @return The specialDms at the given index.
         */
        @Override
        public String getSpecialDms(int index) {
            return instance.getSpecialDms(index);
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the specialDms at the given index.
         */
        @Override
        public com.google.protobuf.ByteString
        getSpecialDmsBytes(int index) {
            return instance.getSpecialDmsBytes(index);
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @param index The index to set the value at.
         * @param value The specialDms to set.
         * @return This builder for chaining.
         */
        public Builder setSpecialDms(
                int index, String value) {
            copyOnWrite();
            instance.setSpecialDms(index, value);
            return this;
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @param value The specialDms to add.
         * @return This builder for chaining.
         */
        public Builder addSpecialDms(
                String value) {
            copyOnWrite();
            instance.addSpecialDms(value);
            return this;
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @param values The specialDms to add.
         * @return This builder for chaining.
         */
        public Builder addAllSpecialDms(
                Iterable<String> values) {
            copyOnWrite();
            instance.addAllSpecialDms(values);
            return this;
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSpecialDms() {
            copyOnWrite();
            instance.clearSpecialDms();
            return this;
        }

        /**
         * <code>repeated string specialDms = 6;</code>
         *
         * @param value The bytes of the specialDms to add.
         * @return This builder for chaining.
         */
        public Builder addSpecialDmsBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.addSpecialDmsBytes(value);
            return this;
        }

        /**
         * <code>optional bool checkBox = 7;</code>
         *
         * @return Whether the checkBox field is set.
         */
        @Override
        public boolean hasCheckBox() {
            return instance.hasCheckBox();
        }

        /**
         * <code>optional bool checkBox = 7;</code>
         *
         * @return The checkBox.
         */
        @Override
        public boolean getCheckBox() {
            return instance.getCheckBox();
        }

        /**
         * <code>optional bool checkBox = 7;</code>
         *
         * @param value The checkBox to set.
         * @return This builder for chaining.
         */
        public Builder setCheckBox(boolean value) {
            copyOnWrite();
            instance.setCheckBox(value);
            return this;
        }

        /**
         * <code>optional bool checkBox = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCheckBox() {
            copyOnWrite();
            instance.clearCheckBox();
            return this;
        }

        /**
         * <code>optional int64 count = 8;</code>
         *
         * @return Whether the count field is set.
         */
        @Override
        public boolean hasCount() {
            return instance.hasCount();
        }

        /**
         * <code>optional int64 count = 8;</code>
         *
         * @return The count.
         */
        @Override
        public long getCount() {
            return instance.getCount();
        }

        /**
         * <code>optional int64 count = 8;</code>
         *
         * @param value The count to set.
         * @return This builder for chaining.
         */
        public Builder setCount(long value) {
            copyOnWrite();
            instance.setCount(value);
            return this;
        }

        /**
         * <code>optional int64 count = 8;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCount() {
            copyOnWrite();
            instance.clearCount();
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        @Override
        public java.util.List<CommandDm> getCommandDmsList() {
            return java.util.Collections.unmodifiableList(
                    instance.getCommandDmsList());
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        @Override
        public int getCommandDmsCount() {
            return instance.getCommandDmsCount();
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        @Override
        public CommandDm getCommandDms(int index) {
            return instance.getCommandDms(index);
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder setCommandDms(
                int index, CommandDm value) {
            copyOnWrite();
            instance.setCommandDms(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder setCommandDms(
                int index, CommandDm.Builder builderForValue) {
            copyOnWrite();
            instance.setCommandDms(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder addCommandDms(CommandDm value) {
            copyOnWrite();
            instance.addCommandDms(value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder addCommandDms(
                int index, CommandDm value) {
            copyOnWrite();
            instance.addCommandDms(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder addCommandDms(
                CommandDm.Builder builderForValue) {
            copyOnWrite();
            instance.addCommandDms(builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder addCommandDms(
                int index, CommandDm.Builder builderForValue) {
            copyOnWrite();
            instance.addCommandDms(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder addAllCommandDms(
                Iterable<? extends CommandDm> values) {
            copyOnWrite();
            instance.addAllCommandDms(values);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder clearCommandDms() {
            copyOnWrite();
            instance.clearCommandDms();
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.CommandDm commandDms = 9;</code>
         */
        public Builder removeCommandDms(int index) {
            copyOnWrite();
            instance.removeCommandDms(index);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
         */
        @Override
        public boolean hasDmSetting() {
            return instance.hasDmSetting();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
         */
        @Override
        public DanmuWebPlayerConfig getDmSetting() {
            return instance.getDmSetting();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
         */
        public Builder setDmSetting(DanmuWebPlayerConfig value) {
            copyOnWrite();
            instance.setDmSetting(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
         */
        public Builder setDmSetting(
                DanmuWebPlayerConfig.Builder builderForValue) {
            copyOnWrite();
            instance.setDmSetting(builderForValue.build());
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
         */
        public Builder mergeDmSetting(DanmuWebPlayerConfig value) {
            copyOnWrite();
            instance.mergeDmSetting(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.DanmuWebPlayerConfig dmSetting = 10;</code>
         */
        public Builder clearDmSetting() {
            copyOnWrite();
            instance.clearDmSetting();
            return this;
        }

        /**
         * <code>optional string reportFilter = 11;</code>
         *
         * @return Whether the reportFilter field is set.
         */
        @Override
        public boolean hasReportFilter() {
            return instance.hasReportFilter();
        }

        /**
         * <code>optional string reportFilter = 11;</code>
         *
         * @return The reportFilter.
         */
        @Override
        public String getReportFilter() {
            return instance.getReportFilter();
        }

        /**
         * <code>optional string reportFilter = 11;</code>
         *
         * @return The bytes for reportFilter.
         */
        @Override
        public com.google.protobuf.ByteString
        getReportFilterBytes() {
            return instance.getReportFilterBytes();
        }

        /**
         * <code>optional string reportFilter = 11;</code>
         *
         * @param value The reportFilter to set.
         * @return This builder for chaining.
         */
        public Builder setReportFilter(
                String value) {
            copyOnWrite();
            instance.setReportFilter(value);
            return this;
        }

        /**
         * <code>optional string reportFilter = 11;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearReportFilter() {
            copyOnWrite();
            instance.clearReportFilter();
            return this;
        }

        /**
         * <code>optional string reportFilter = 11;</code>
         *
         * @param value The bytes for reportFilter to set.
         * @return This builder for chaining.
         */
        public Builder setReportFilterBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setReportFilterBytes(value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        @Override
        public java.util.List<Expressions> getExpressionsList() {
            return java.util.Collections.unmodifiableList(
                    instance.getExpressionsList());
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        @Override
        public int getExpressionsCount() {
            return instance.getExpressionsCount();
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        @Override
        public Expressions getExpressions(int index) {
            return instance.getExpressions(index);
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder setExpressions(
                int index, Expressions value) {
            copyOnWrite();
            instance.setExpressions(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder setExpressions(
                int index, Expressions.Builder builderForValue) {
            copyOnWrite();
            instance.setExpressions(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder addExpressions(Expressions value) {
            copyOnWrite();
            instance.addExpressions(value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder addExpressions(
                int index, Expressions value) {
            copyOnWrite();
            instance.addExpressions(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder addExpressions(
                Expressions.Builder builderForValue) {
            copyOnWrite();
            instance.addExpressions(builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder addExpressions(
                int index, Expressions.Builder builderForValue) {
            copyOnWrite();
            instance.addExpressions(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder addAllExpressions(
                Iterable<? extends Expressions> values) {
            copyOnWrite();
            instance.addAllExpressions(values);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder clearExpressions() {
            copyOnWrite();
            instance.clearExpressions();
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expressions expressions = 12;</code>
         */
        public Builder removeExpressions(int index) {
            copyOnWrite();
            instance.removeExpressions(index);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        @Override
        public java.util.List<PostPanel> getPostPanelList() {
            return java.util.Collections.unmodifiableList(
                    instance.getPostPanelList());
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        @Override
        public int getPostPanelCount() {
            return instance.getPostPanelCount();
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        @Override
        public PostPanel getPostPanel(int index) {
            return instance.getPostPanel(index);
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder setPostPanel(
                int index, PostPanel value) {
            copyOnWrite();
            instance.setPostPanel(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder setPostPanel(
                int index, PostPanel.Builder builderForValue) {
            copyOnWrite();
            instance.setPostPanel(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder addPostPanel(PostPanel value) {
            copyOnWrite();
            instance.addPostPanel(value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder addPostPanel(
                int index, PostPanel value) {
            copyOnWrite();
            instance.addPostPanel(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder addPostPanel(
                PostPanel.Builder builderForValue) {
            copyOnWrite();
            instance.addPostPanel(builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder addPostPanel(
                int index, PostPanel.Builder builderForValue) {
            copyOnWrite();
            instance.addPostPanel(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder addAllPostPanel(
                Iterable<? extends PostPanel> values) {
            copyOnWrite();
            instance.addAllPostPanel(values);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder clearPostPanel() {
            copyOnWrite();
            instance.clearPostPanel();
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.PostPanel postPanel = 13;</code>
         */
        public Builder removePostPanel(int index) {
            copyOnWrite();
            instance.removePostPanel(index);
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.DmWebViewReply)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new DmWebViewReply();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "state_",
                        "text_",
                        "textSide_",
                        "dmSge_",
                        "flag_",
                        "specialDms_",
                        "checkBox_",
                        "count_",
                        "commandDms_",
                        CommandDm.class,
                        "dmSetting_",
                        "reportFilter_",
                        "expressions_",
                        Expressions.class,
                        "postPanel_",
                        PostPanel.class,
                };
                String info =
                        "\u0000\r\u0000\u0001\u0001\r\r\u0000\u0004\u0000\u0001\u1004\u0000\u0002\u1208\u0001" +
                                "\u0003\u1208\u0002\u0004\u1009\u0003\u0005\u1009\u0004\u0006\u021a\u0007\u1007\u0005" +
                                "\b\u1002\u0006\t\u001b\n\u1009\u0007\u000b\u1208\b\f\u001b\r\u001b";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<DmWebViewReply> parser = PARSER;
                if (parser == null) {
                    synchronized (DmWebViewReply.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<DmWebViewReply>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.DmWebViewReply)
    private static final DmWebViewReply DEFAULT_INSTANCE;

    static {
        DmWebViewReply defaultInstance = new DmWebViewReply();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                DmWebViewReply.class, defaultInstance);
    }

    public static DmWebViewReply getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<DmWebViewReply> PARSER;

    public static com.google.protobuf.Parser<DmWebViewReply> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

