// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Expressions}
 */
public final class Expressions extends
        com.google.protobuf.GeneratedMessageLite<
                Expressions, Expressions.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.Expressions)
        ExpressionsOrBuilder {
    private Expressions() {
        data_ = emptyProtobufList();
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<Expression> data_;

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    @Override
    public java.util.List<Expression> getDataList() {
        return data_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    public java.util.List<? extends ExpressionOrBuilder>
    getDataOrBuilderList() {
        return data_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    @Override
    public int getDataCount() {
        return data_.size();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    @Override
    public Expression getData(int index) {
        return data_.get(index);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    public ExpressionOrBuilder getDataOrBuilder(
            int index) {
        return data_.get(index);
    }

    private void ensureDataIsMutable() {
        com.google.protobuf.Internal.ProtobufList<Expression> tmp = data_;
        if (!tmp.isModifiable()) {
            data_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    private void setData(
            int index, Expression value) {
        value.getClass();
        ensureDataIsMutable();
        data_.set(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    private void addData(Expression value) {
        value.getClass();
        ensureDataIsMutable();
        data_.add(value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    private void addData(
            int index, Expression value) {
        value.getClass();
        ensureDataIsMutable();
        data_.add(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    private void addAllData(
            Iterable<? extends Expression> values) {
        ensureDataIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, data_);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    private void clearData() {
        data_ = emptyProtobufList();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
     */
    private void removeData(int index) {
        ensureDataIsMutable();
        data_.remove(index);
    }

    public static Expressions parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Expressions parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Expressions parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Expressions parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Expressions parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Expressions parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Expressions parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Expressions parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Expressions parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Expressions parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Expressions parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Expressions parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(Expressions prototype) {
        return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Expressions}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    Expressions, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.Expressions)
            ExpressionsOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.Expressions.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        @Override
        public java.util.List<Expression> getDataList() {
            return java.util.Collections.unmodifiableList(
                    instance.getDataList());
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        @Override
        public int getDataCount() {
            return instance.getDataCount();
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        @Override
        public Expression getData(int index) {
            return instance.getData(index);
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder setData(
                int index, Expression value) {
            copyOnWrite();
            instance.setData(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder setData(
                int index, Expression.Builder builderForValue) {
            copyOnWrite();
            instance.setData(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder addData(Expression value) {
            copyOnWrite();
            instance.addData(value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder addData(
                int index, Expression value) {
            copyOnWrite();
            instance.addData(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder addData(
                Expression.Builder builderForValue) {
            copyOnWrite();
            instance.addData(builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder addData(
                int index, Expression.Builder builderForValue) {
            copyOnWrite();
            instance.addData(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder addAllData(
                Iterable<? extends Expression> values) {
            copyOnWrite();
            instance.addAllData(values);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder clearData() {
            copyOnWrite();
            instance.clearData();
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Expression data = 1;</code>
         */
        public Builder removeData(int index) {
            copyOnWrite();
            instance.removeData(index);
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.Expressions)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new Expressions();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "data_",
                        Expression.class,
                };
                String info =
                        "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<Expressions> parser = PARSER;
                if (parser == null) {
                    synchronized (Expressions.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<Expressions>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.Expressions)
    private static final Expressions DEFAULT_INSTANCE;

    static {
        Expressions defaultInstance = new Expressions();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                Expressions.class, defaultInstance);
    }

    public static Expressions getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Expressions> PARSER;

    public static com.google.protobuf.Parser<Expressions> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

