// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Expression}
 */
public final class Expression extends
        com.google.protobuf.GeneratedMessageLite<
                Expression, Expression.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.Expression)
        ExpressionOrBuilder {
    private Expression() {
        keyword_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        url_ = "";
        period_ = emptyProtobufList();
    }

    private int bitField0_;
    public static final int KEYWORD_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<String> keyword_;

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @return A list containing the keyword.
     */
    @Override
    public java.util.List<String> getKeywordList() {
        return keyword_;
    }

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @return The count of keyword.
     */
    @Override
    public int getKeywordCount() {
        return keyword_.size();
    }

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The keyword at the given index.
     */
    @Override
    public String getKeyword(int index) {
        return keyword_.get(index);
    }

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the keyword at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
    getKeywordBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
                keyword_.get(index));
    }

    private void ensureKeywordIsMutable() {
        com.google.protobuf.Internal.ProtobufList<String> tmp =
                keyword_;
        if (!tmp.isModifiable()) {
            keyword_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @param index The index to set the value at.
     * @param value The keyword to set.
     */
    private void setKeyword(
            int index, String value) {
        Class<?> valueClass = value.getClass();
        ensureKeywordIsMutable();
        keyword_.set(index, value);
    }

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @param value The keyword to add.
     */
    private void addKeyword(
            String value) {
        Class<?> valueClass = value.getClass();
        ensureKeywordIsMutable();
        keyword_.add(value);
    }

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @param values The keyword to add.
     */
    private void addAllKeyword(
            Iterable<String> values) {
        ensureKeywordIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, keyword_);
    }

    /**
     * <code>repeated string keyword = 1;</code>
     */
    private void clearKeyword() {
        keyword_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @param value The bytes of the keyword to add.
     */
    private void addKeywordBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensureKeywordIsMutable();
        keyword_.add(value.toStringUtf8());
    }

    public static final int URL_FIELD_NUMBER = 2;
    private String url_;

    /**
     * <code>optional string url = 2;</code>
     *
     * @return Whether the url field is set.
     */
    @Override
    public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional string url = 2;</code>
     *
     * @return The url.
     */
    @Override
    public String getUrl() {
        return url_;
    }

    /**
     * <code>optional string url = 2;</code>
     *
     * @return The bytes for url.
     */
    @Override
    public com.google.protobuf.ByteString
    getUrlBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(url_);
    }

    /**
     * <code>optional string url = 2;</code>
     *
     * @param value The url to set.
     */
    private void setUrl(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000001;
        url_ = value;
    }

    /**
     * <code>optional string url = 2;</code>
     */
    private void clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
    }

    /**
     * <code>optional string url = 2;</code>
     *
     * @param value The bytes for url to set.
     */
    private void setUrlBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        url_ = value.toStringUtf8();
        bitField0_ |= 0x00000001;
    }

    public static final int PERIOD_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<Period> period_;

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    @Override
    public java.util.List<Period> getPeriodList() {
        return period_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    public java.util.List<? extends PeriodOrBuilder>
    getPeriodOrBuilderList() {
        return period_;
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    @Override
    public int getPeriodCount() {
        return period_.size();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    @Override
    public Period getPeriod(int index) {
        return period_.get(index);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    public PeriodOrBuilder getPeriodOrBuilder(
            int index) {
        return period_.get(index);
    }

    private void ensurePeriodIsMutable() {
        com.google.protobuf.Internal.ProtobufList<Period> tmp = period_;
        if (!tmp.isModifiable()) {
            period_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    private void setPeriod(
            int index, Period value) {
        value.getClass();
        ensurePeriodIsMutable();
        period_.set(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    private void addPeriod(Period value) {
        value.getClass();
        ensurePeriodIsMutable();
        period_.add(value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    private void addPeriod(
            int index, Period value) {
        value.getClass();
        ensurePeriodIsMutable();
        period_.add(index, value);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    private void addAllPeriod(
            Iterable<? extends Period> values) {
        ensurePeriodIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, period_);
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    private void clearPeriod() {
        period_ = emptyProtobufList();
    }

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    private void removePeriod(int index) {
        ensurePeriodIsMutable();
        period_.remove(index);
    }

    public static Expression parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Expression parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Expression parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Expression parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Expression parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Expression parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Expression parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Expression parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Expression parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Expression parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Expression parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Expression parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(Expression prototype) {
        return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Expression}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    Expression, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.Expression)
            ExpressionOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.Expression.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @return A list containing the keyword.
         */
        @Override
        public java.util.List<String>
        getKeywordList() {
            return java.util.Collections.unmodifiableList(
                    instance.getKeywordList());
        }

        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @return The count of keyword.
         */
        @Override
        public int getKeywordCount() {
            return instance.getKeywordCount();
        }

        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The keyword at the given index.
         */
        @Override
        public String getKeyword(int index) {
            return instance.getKeyword(index);
        }

        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the keyword at the given index.
         */
        @Override
        public com.google.protobuf.ByteString
        getKeywordBytes(int index) {
            return instance.getKeywordBytes(index);
        }

        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @param index The index to set the value at.
         * @param value The keyword to set.
         * @return This builder for chaining.
         */
        public Builder setKeyword(
                int index, String value) {
            copyOnWrite();
            instance.setKeyword(index, value);
            return this;
        }

        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @param value The keyword to add.
         * @return This builder for chaining.
         */
        public Builder addKeyword(
                String value) {
            copyOnWrite();
            instance.addKeyword(value);
            return this;
        }

        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @param values The keyword to add.
         * @return This builder for chaining.
         */
        public Builder addAllKeyword(
                Iterable<String> values) {
            copyOnWrite();
            instance.addAllKeyword(values);
            return this;
        }

        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearKeyword() {
            copyOnWrite();
            instance.clearKeyword();
            return this;
        }

        /**
         * <code>repeated string keyword = 1;</code>
         *
         * @param value The bytes of the keyword to add.
         * @return This builder for chaining.
         */
        public Builder addKeywordBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.addKeywordBytes(value);
            return this;
        }

        /**
         * <code>optional string url = 2;</code>
         *
         * @return Whether the url field is set.
         */
        @Override
        public boolean hasUrl() {
            return instance.hasUrl();
        }

        /**
         * <code>optional string url = 2;</code>
         *
         * @return The url.
         */
        @Override
        public String getUrl() {
            return instance.getUrl();
        }

        /**
         * <code>optional string url = 2;</code>
         *
         * @return The bytes for url.
         */
        @Override
        public com.google.protobuf.ByteString
        getUrlBytes() {
            return instance.getUrlBytes();
        }

        /**
         * <code>optional string url = 2;</code>
         *
         * @param value The url to set.
         * @return This builder for chaining.
         */
        public Builder setUrl(
                String value) {
            copyOnWrite();
            instance.setUrl(value);
            return this;
        }

        /**
         * <code>optional string url = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUrl() {
            copyOnWrite();
            instance.clearUrl();
            return this;
        }

        /**
         * <code>optional string url = 2;</code>
         *
         * @param value The bytes for url to set.
         * @return This builder for chaining.
         */
        public Builder setUrlBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setUrlBytes(value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        @Override
        public java.util.List<Period> getPeriodList() {
            return java.util.Collections.unmodifiableList(
                    instance.getPeriodList());
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        @Override
        public int getPeriodCount() {
            return instance.getPeriodCount();
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        @Override
        public Period getPeriod(int index) {
            return instance.getPeriod(index);
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder setPeriod(
                int index, Period value) {
            copyOnWrite();
            instance.setPeriod(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder setPeriod(
                int index, Period.Builder builderForValue) {
            copyOnWrite();
            instance.setPeriod(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder addPeriod(Period value) {
            copyOnWrite();
            instance.addPeriod(value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder addPeriod(
                int index, Period value) {
            copyOnWrite();
            instance.addPeriod(index, value);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder addPeriod(
                Period.Builder builderForValue) {
            copyOnWrite();
            instance.addPeriod(builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder addPeriod(
                int index, Period.Builder builderForValue) {
            copyOnWrite();
            instance.addPeriod(index,
                    builderForValue.build());
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder addAllPeriod(
                Iterable<? extends Period> values) {
            copyOnWrite();
            instance.addAllPeriod(values);
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder clearPeriod() {
            copyOnWrite();
            instance.clearPeriod();
            return this;
        }

        /**
         * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
         */
        public Builder removePeriod(int index) {
            copyOnWrite();
            instance.removePeriod(index);
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.Expression)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new Expression();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "keyword_",
                        "url_",
                        "period_",
                        Period.class,
                };
                String info =
                        "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0002\u0000\u0001\u021a\u0002\u1208" +
                                "\u0000\u0003\u001b";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<Expression> parser = PARSER;
                if (parser == null) {
                    synchronized (Expression.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<Expression>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.Expression)
    private static final Expression DEFAULT_INSTANCE;

    static {
        Expression defaultInstance = new Expression();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                Expression.class, defaultInstance);
    }

    public static Expression getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Expression> PARSER;

    public static com.google.protobuf.Parser<Expression> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

