// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface ExpressionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.Expression)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @return A list containing the keyword.
     */
    java.util.List<String>
    getKeywordList();

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @return The count of keyword.
     */
    int getKeywordCount();

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The keyword at the given index.
     */
    String getKeyword(int index);

    /**
     * <code>repeated string keyword = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The keyword at the given index.
     */
    com.google.protobuf.ByteString
    getKeywordBytes(int index);

    /**
     * <code>optional string url = 2;</code>
     *
     * @return Whether the url field is set.
     */
    boolean hasUrl();

    /**
     * <code>optional string url = 2;</code>
     *
     * @return The url.
     */
    String getUrl();

    /**
     * <code>optional string url = 2;</code>
     *
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
    getUrlBytes();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    java.util.List<Period>
    getPeriodList();

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    Period getPeriod(int index);

    /**
     * <code>repeated .com.muedsa.bilibililiveapiclient.model.Period period = 3;</code>
     */
    int getPeriodCount();
}
