// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Period}
 */
public final class Period extends
        com.google.protobuf.GeneratedMessageLite<
                Period, Period.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.Period)
        PeriodOrBuilder {
    private Period() {
    }

    private int bitField0_;
    public static final int START_FIELD_NUMBER = 1;
    private long start_;

    /**
     * <code>optional int64 start = 1;</code>
     *
     * @return Whether the start field is set.
     */
    @Override
    public boolean hasStart() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional int64 start = 1;</code>
     *
     * @return The start.
     */
    @Override
    public long getStart() {
        return start_;
    }

    /**
     * <code>optional int64 start = 1;</code>
     *
     * @param value The start to set.
     */
    private void setStart(long value) {
        bitField0_ |= 0x00000001;
        start_ = value;
    }

    /**
     * <code>optional int64 start = 1;</code>
     */
    private void clearStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = 0L;
    }

    public static final int END_FIELD_NUMBER = 2;
    private long end_;

    /**
     * <code>optional int64 end = 2;</code>
     *
     * @return Whether the end field is set.
     */
    @Override
    public boolean hasEnd() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional int64 end = 2;</code>
     *
     * @return The end.
     */
    @Override
    public long getEnd() {
        return end_;
    }

    /**
     * <code>optional int64 end = 2;</code>
     *
     * @param value The end to set.
     */
    private void setEnd(long value) {
        bitField0_ |= 0x00000002;
        end_ = value;
    }

    /**
     * <code>optional int64 end = 2;</code>
     */
    private void clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        end_ = 0L;
    }

    public static Period parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Period parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Period parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Period parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Period parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Period parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Period parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Period parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Period parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Period parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Period parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Period parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(Period prototype) {
        return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Period}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    Period, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.Period)
            PeriodOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.Period.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional int64 start = 1;</code>
         *
         * @return Whether the start field is set.
         */
        @Override
        public boolean hasStart() {
            return instance.hasStart();
        }

        /**
         * <code>optional int64 start = 1;</code>
         *
         * @return The start.
         */
        @Override
        public long getStart() {
            return instance.getStart();
        }

        /**
         * <code>optional int64 start = 1;</code>
         *
         * @param value The start to set.
         * @return This builder for chaining.
         */
        public Builder setStart(long value) {
            copyOnWrite();
            instance.setStart(value);
            return this;
        }

        /**
         * <code>optional int64 start = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStart() {
            copyOnWrite();
            instance.clearStart();
            return this;
        }

        /**
         * <code>optional int64 end = 2;</code>
         *
         * @return Whether the end field is set.
         */
        @Override
        public boolean hasEnd() {
            return instance.hasEnd();
        }

        /**
         * <code>optional int64 end = 2;</code>
         *
         * @return The end.
         */
        @Override
        public long getEnd() {
            return instance.getEnd();
        }

        /**
         * <code>optional int64 end = 2;</code>
         *
         * @param value The end to set.
         * @return This builder for chaining.
         */
        public Builder setEnd(long value) {
            copyOnWrite();
            instance.setEnd(value);
            return this;
        }

        /**
         * <code>optional int64 end = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearEnd() {
            copyOnWrite();
            instance.clearEnd();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.Period)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new Period();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "start_",
                        "end_",
                };
                String info =
                        "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1002\u0000\u0002" +
                                "\u1002\u0001";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<Period> parser = PARSER;
                if (parser == null) {
                    synchronized (Period.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<Period>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.Period)
    private static final Period DEFAULT_INSTANCE;

    static {
        Period defaultInstance = new Period();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                Period.class, defaultInstance);
    }

    public static Period getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Period> PARSER;

    public static com.google.protobuf.Parser<Period> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

