// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.PostPanel}
 */
public final class PostPanel extends
        com.google.protobuf.GeneratedMessageLite<
                PostPanel, PostPanel.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.PostPanel)
        PostPanelOrBuilder {
    private PostPanel() {
    }

    private int bitField0_;
    public static final int START_FIELD_NUMBER = 1;
    private long start_;

    /**
     * <code>optional int64 start = 1;</code>
     *
     * @return Whether the start field is set.
     */
    @Override
    public boolean hasStart() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional int64 start = 1;</code>
     *
     * @return The start.
     */
    @Override
    public long getStart() {
        return start_;
    }

    /**
     * <code>optional int64 start = 1;</code>
     *
     * @param value The start to set.
     */
    private void setStart(long value) {
        bitField0_ |= 0x00000001;
        start_ = value;
    }

    /**
     * <code>optional int64 start = 1;</code>
     */
    private void clearStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = 0L;
    }

    public static final int END_FIELD_NUMBER = 2;
    private long end_;

    /**
     * <code>optional int64 end = 2;</code>
     *
     * @return Whether the end field is set.
     */
    @Override
    public boolean hasEnd() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional int64 end = 2;</code>
     *
     * @return The end.
     */
    @Override
    public long getEnd() {
        return end_;
    }

    /**
     * <code>optional int64 end = 2;</code>
     *
     * @param value The end to set.
     */
    private void setEnd(long value) {
        bitField0_ |= 0x00000002;
        end_ = value;
    }

    /**
     * <code>optional int64 end = 2;</code>
     */
    private void clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        end_ = 0L;
    }

    public static final int PRIORITY_FIELD_NUMBER = 3;
    private long priority_;

    /**
     * <code>optional int64 priority = 3;</code>
     *
     * @return Whether the priority field is set.
     */
    @Override
    public boolean hasPriority() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>optional int64 priority = 3;</code>
     *
     * @return The priority.
     */
    @Override
    public long getPriority() {
        return priority_;
    }

    /**
     * <code>optional int64 priority = 3;</code>
     *
     * @param value The priority to set.
     */
    private void setPriority(long value) {
        bitField0_ |= 0x00000004;
        priority_ = value;
    }

    /**
     * <code>optional int64 priority = 3;</code>
     */
    private void clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000004);
        priority_ = 0L;
    }

    public static final int BIZID_FIELD_NUMBER = 4;
    private long bizId_;

    /**
     * <code>optional int64 bizId = 4;</code>
     *
     * @return Whether the bizId field is set.
     */
    @Override
    public boolean hasBizId() {
        return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <code>optional int64 bizId = 4;</code>
     *
     * @return The bizId.
     */
    @Override
    public long getBizId() {
        return bizId_;
    }

    /**
     * <code>optional int64 bizId = 4;</code>
     *
     * @param value The bizId to set.
     */
    private void setBizId(long value) {
        bitField0_ |= 0x00000008;
        bizId_ = value;
    }

    /**
     * <code>optional int64 bizId = 4;</code>
     */
    private void clearBizId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bizId_ = 0L;
    }

    public static final int BIZTYPE_FIELD_NUMBER = 5;
    private int bizType_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     *
     * @return Whether the bizType field is set.
     */
    @Override
    public boolean hasBizType() {
        return ((bitField0_ & 0x00000010) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     *
     * @return The enum numeric value on the wire for bizType.
     */
    @Override
    public int getBizTypeValue() {
        return bizType_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     *
     * @return The bizType.
     */
    @Override
    public PostPanelBizType getBizType() {
        PostPanelBizType result = PostPanelBizType.forNumber(bizType_);
        return result == null ? PostPanelBizType.UNRECOGNIZED : result;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     *
     * @param value The enum numeric value on the wire for bizType to set.
     */
    private void setBizTypeValue(int value) {
        bitField0_ |= 0x00000010;
        bizType_ = value;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     *
     * @param value The bizType to set.
     */
    private void setBizType(PostPanelBizType value) {
        bizType_ = value.getNumber();
        bitField0_ |= 0x00000010;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     */
    private void clearBizType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bizType_ = 0;
    }

    public static final int CLICKBUTTON_FIELD_NUMBER = 6;
    private ClickButton clickButton_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
     */
    @Override
    public boolean hasClickButton() {
        return ((bitField0_ & 0x00000020) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
     */
    @Override
    public ClickButton getClickButton() {
        return clickButton_ == null ? ClickButton.getDefaultInstance() : clickButton_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
     */
    private void setClickButton(ClickButton value) {
        value.getClass();
        clickButton_ = value;
        bitField0_ |= 0x00000020;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeClickButton(ClickButton value) {
        value.getClass();
        if (clickButton_ != null &&
                clickButton_ != ClickButton.getDefaultInstance()) {
            clickButton_ =
                    ClickButton.newBuilder(clickButton_).mergeFrom(value).buildPartial();
        } else {
            clickButton_ = value;
        }
        bitField0_ |= 0x00000020;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
     */
    private void clearClickButton() {
        clickButton_ = null;
        bitField0_ = (bitField0_ & ~0x00000020);
    }

    public static final int TEXTINPUT_FIELD_NUMBER = 7;
    private TextInput textInput_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
     */
    @Override
    public boolean hasTextInput() {
        return ((bitField0_ & 0x00000040) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
     */
    @Override
    public TextInput getTextInput() {
        return textInput_ == null ? TextInput.getDefaultInstance() : textInput_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
     */
    private void setTextInput(TextInput value) {
        value.getClass();
        textInput_ = value;
        bitField0_ |= 0x00000040;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeTextInput(TextInput value) {
        value.getClass();
        if (textInput_ != null &&
                textInput_ != TextInput.getDefaultInstance()) {
            textInput_ =
                    TextInput.newBuilder(textInput_).mergeFrom(value).buildPartial();
        } else {
            textInput_ = value;
        }
        bitField0_ |= 0x00000040;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
     */
    private void clearTextInput() {
        textInput_ = null;
        bitField0_ = (bitField0_ & ~0x00000040);
    }

    public static final int CHECKBOX_FIELD_NUMBER = 8;
    private CheckBox checkBox_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
     */
    @Override
    public boolean hasCheckBox() {
        return ((bitField0_ & 0x00000080) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
     */
    @Override
    public CheckBox getCheckBox() {
        return checkBox_ == null ? CheckBox.getDefaultInstance() : checkBox_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
     */
    private void setCheckBox(CheckBox value) {
        value.getClass();
        checkBox_ = value;
        bitField0_ |= 0x00000080;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeCheckBox(CheckBox value) {
        value.getClass();
        if (checkBox_ != null &&
                checkBox_ != CheckBox.getDefaultInstance()) {
            checkBox_ =
                    CheckBox.newBuilder(checkBox_).mergeFrom(value).buildPartial();
        } else {
            checkBox_ = value;
        }
        bitField0_ |= 0x00000080;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
     */
    private void clearCheckBox() {
        checkBox_ = null;
        bitField0_ = (bitField0_ & ~0x00000080);
    }

    public static final int TOAST_FIELD_NUMBER = 9;
    private Toast toast_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
     */
    @Override
    public boolean hasToast() {
        return ((bitField0_ & 0x00000100) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
     */
    @Override
    public Toast getToast() {
        return toast_ == null ? Toast.getDefaultInstance() : toast_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
     */
    private void setToast(Toast value) {
        value.getClass();
        toast_ = value;
        bitField0_ |= 0x00000100;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeToast(Toast value) {
        value.getClass();
        if (toast_ != null &&
                toast_ != Toast.getDefaultInstance()) {
            toast_ =
                    Toast.newBuilder(toast_).mergeFrom(value).buildPartial();
        } else {
            toast_ = value;
        }
        bitField0_ |= 0x00000100;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
     */
    private void clearToast() {
        toast_ = null;
        bitField0_ = (bitField0_ & ~0x00000100);
    }

    public static PostPanel parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static PostPanel parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static PostPanel parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static PostPanel parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static PostPanel parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static PostPanel parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static PostPanel parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static PostPanel parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static PostPanel parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static PostPanel parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static PostPanel parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static PostPanel parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(PostPanel prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.PostPanel}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    PostPanel, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.PostPanel)
            PostPanelOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.PostPanel.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional int64 start = 1;</code>
         *
         * @return Whether the start field is set.
         */
        @Override
        public boolean hasStart() {
            return instance.hasStart();
        }

        /**
         * <code>optional int64 start = 1;</code>
         *
         * @return The start.
         */
        @Override
        public long getStart() {
            return instance.getStart();
        }

        /**
         * <code>optional int64 start = 1;</code>
         *
         * @param value The start to set.
         * @return This builder for chaining.
         */
        public Builder setStart(long value) {
            copyOnWrite();
            instance.setStart(value);
            return this;
        }

        /**
         * <code>optional int64 start = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearStart() {
            copyOnWrite();
            instance.clearStart();
            return this;
        }

        /**
         * <code>optional int64 end = 2;</code>
         *
         * @return Whether the end field is set.
         */
        @Override
        public boolean hasEnd() {
            return instance.hasEnd();
        }

        /**
         * <code>optional int64 end = 2;</code>
         *
         * @return The end.
         */
        @Override
        public long getEnd() {
            return instance.getEnd();
        }

        /**
         * <code>optional int64 end = 2;</code>
         *
         * @param value The end to set.
         * @return This builder for chaining.
         */
        public Builder setEnd(long value) {
            copyOnWrite();
            instance.setEnd(value);
            return this;
        }

        /**
         * <code>optional int64 end = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearEnd() {
            copyOnWrite();
            instance.clearEnd();
            return this;
        }

        /**
         * <code>optional int64 priority = 3;</code>
         *
         * @return Whether the priority field is set.
         */
        @Override
        public boolean hasPriority() {
            return instance.hasPriority();
        }

        /**
         * <code>optional int64 priority = 3;</code>
         *
         * @return The priority.
         */
        @Override
        public long getPriority() {
            return instance.getPriority();
        }

        /**
         * <code>optional int64 priority = 3;</code>
         *
         * @param value The priority to set.
         * @return This builder for chaining.
         */
        public Builder setPriority(long value) {
            copyOnWrite();
            instance.setPriority(value);
            return this;
        }

        /**
         * <code>optional int64 priority = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPriority() {
            copyOnWrite();
            instance.clearPriority();
            return this;
        }

        /**
         * <code>optional int64 bizId = 4;</code>
         *
         * @return Whether the bizId field is set.
         */
        @Override
        public boolean hasBizId() {
            return instance.hasBizId();
        }

        /**
         * <code>optional int64 bizId = 4;</code>
         *
         * @return The bizId.
         */
        @Override
        public long getBizId() {
            return instance.getBizId();
        }

        /**
         * <code>optional int64 bizId = 4;</code>
         *
         * @param value The bizId to set.
         * @return This builder for chaining.
         */
        public Builder setBizId(long value) {
            copyOnWrite();
            instance.setBizId(value);
            return this;
        }

        /**
         * <code>optional int64 bizId = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearBizId() {
            copyOnWrite();
            instance.clearBizId();
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
         *
         * @return Whether the bizType field is set.
         */
        @Override
        public boolean hasBizType() {
            return instance.hasBizType();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
         *
         * @return The enum numeric value on the wire for bizType.
         */
        @Override
        public int getBizTypeValue() {
            return instance.getBizTypeValue();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
         *
         * @param value The bizType to set.
         * @return This builder for chaining.
         */
        public Builder setBizTypeValue(int value) {
            copyOnWrite();
            instance.setBizTypeValue(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
         *
         * @return The bizType.
         */
        @Override
        public PostPanelBizType getBizType() {
            return instance.getBizType();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
         *
         * @param value The enum numeric value on the wire for bizType to set.
         * @return This builder for chaining.
         */
        public Builder setBizType(PostPanelBizType value) {
            copyOnWrite();
            instance.setBizType(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearBizType() {
            copyOnWrite();
            instance.clearBizType();
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
         */
        @Override
        public boolean hasClickButton() {
            return instance.hasClickButton();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
         */
        @Override
        public ClickButton getClickButton() {
            return instance.getClickButton();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
         */
        public Builder setClickButton(ClickButton value) {
            copyOnWrite();
            instance.setClickButton(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
         */
        public Builder setClickButton(
                ClickButton.Builder builderForValue) {
            copyOnWrite();
            instance.setClickButton(builderForValue.build());
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
         */
        public Builder mergeClickButton(ClickButton value) {
            copyOnWrite();
            instance.mergeClickButton(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
         */
        public Builder clearClickButton() {
            copyOnWrite();
            instance.clearClickButton();
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
         */
        @Override
        public boolean hasTextInput() {
            return instance.hasTextInput();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
         */
        @Override
        public TextInput getTextInput() {
            return instance.getTextInput();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
         */
        public Builder setTextInput(TextInput value) {
            copyOnWrite();
            instance.setTextInput(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
         */
        public Builder setTextInput(
                TextInput.Builder builderForValue) {
            copyOnWrite();
            instance.setTextInput(builderForValue.build());
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
         */
        public Builder mergeTextInput(TextInput value) {
            copyOnWrite();
            instance.mergeTextInput(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
         */
        public Builder clearTextInput() {
            copyOnWrite();
            instance.clearTextInput();
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
         */
        @Override
        public boolean hasCheckBox() {
            return instance.hasCheckBox();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
         */
        @Override
        public CheckBox getCheckBox() {
            return instance.getCheckBox();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
         */
        public Builder setCheckBox(CheckBox value) {
            copyOnWrite();
            instance.setCheckBox(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
         */
        public Builder setCheckBox(
                CheckBox.Builder builderForValue) {
            copyOnWrite();
            instance.setCheckBox(builderForValue.build());
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
         */
        public Builder mergeCheckBox(CheckBox value) {
            copyOnWrite();
            instance.mergeCheckBox(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
         */
        public Builder clearCheckBox() {
            copyOnWrite();
            instance.clearCheckBox();
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
         */
        @Override
        public boolean hasToast() {
            return instance.hasToast();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
         */
        @Override
        public Toast getToast() {
            return instance.getToast();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
         */
        public Builder setToast(Toast value) {
            copyOnWrite();
            instance.setToast(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
         */
        public Builder setToast(
                Toast.Builder builderForValue) {
            copyOnWrite();
            instance.setToast(builderForValue.build());
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
         */
        public Builder mergeToast(Toast value) {
            copyOnWrite();
            instance.mergeToast(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
         */
        public Builder clearToast() {
            copyOnWrite();
            instance.clearToast();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.PostPanel)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new PostPanel();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "start_",
                        "end_",
                        "priority_",
                        "bizId_",
                        "bizType_",
                        "clickButton_",
                        "textInput_",
                        "checkBox_",
                        "toast_",
                };
                String info =
                        "\u0000\t\u0000\u0001\u0001\t\t\u0000\u0000\u0000\u0001\u1002\u0000\u0002\u1002\u0001" +
                                "\u0003\u1002\u0002\u0004\u1002\u0003\u0005\u100c\u0004\u0006\u1009\u0005\u0007\u1009" +
                                "\u0006\b\u1009\u0007\t\u1009\b";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<PostPanel> parser = PARSER;
                if (parser == null) {
                    synchronized (PostPanel.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<PostPanel>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.PostPanel)
    private static final PostPanel DEFAULT_INSTANCE;

    static {
        PostPanel defaultInstance = new PostPanel();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                PostPanel.class, defaultInstance);
    }

    public static PostPanel getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PostPanel> PARSER;

    public static com.google.protobuf.Parser<PostPanel> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

