// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf enum {@code com.muedsa.bilibililiveapiclient.model.PostPanelBizType}
 */
public enum PostPanelBizType
        implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>PostPanelBizTypeNone = 0;</code>
     */
    PostPanelBizTypeNone(0),
    /**
     * <code>PostPanelBizTypeEncourage = 1;</code>
     */
    PostPanelBizTypeEncourage(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PostPanelBizTypeNone = 0;</code>
     */
    public static final int PostPanelBizTypeNone_VALUE = 0;
    /**
     * <code>PostPanelBizTypeEncourage = 1;</code>
     */
    public static final int PostPanelBizTypeEncourage_VALUE = 1;


    @Override
    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static PostPanelBizType valueOf(int value) {
        return forNumber(value);
    }

    public static PostPanelBizType forNumber(int value) {
        switch (value) {
            case 0:
                return PostPanelBizTypeNone;
            case 1:
                return PostPanelBizTypeEncourage;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PostPanelBizType>
    internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            PostPanelBizType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PostPanelBizType>() {
                @Override
                public PostPanelBizType findValueByNumber(int number) {
                    return PostPanelBizType.forNumber(number);
                }
            };

    public static com.google.protobuf.Internal.EnumVerifier
    internalGetVerifier() {
        return PostPanelBizTypeVerifier.INSTANCE;
    }

    private static final class PostPanelBizTypeVerifier implements
            com.google.protobuf.Internal.EnumVerifier {
        static final com.google.protobuf.Internal.EnumVerifier INSTANCE = new PostPanelBizTypeVerifier();

        @Override
        public boolean isInRange(int number) {
            return PostPanelBizType.forNumber(number) != null;
        }
    }

    private final int value;

    PostPanelBizType(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.muedsa.bilibililiveapiclient.model.PostPanelBizType)
}

