// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

public interface PostPanelOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.muedsa.bilibililiveapiclient.model.PostPanel)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 start = 1;</code>
     *
     * @return Whether the start field is set.
     */
    boolean hasStart();

    /**
     * <code>optional int64 start = 1;</code>
     *
     * @return The start.
     */
    long getStart();

    /**
     * <code>optional int64 end = 2;</code>
     *
     * @return Whether the end field is set.
     */
    boolean hasEnd();

    /**
     * <code>optional int64 end = 2;</code>
     *
     * @return The end.
     */
    long getEnd();

    /**
     * <code>optional int64 priority = 3;</code>
     *
     * @return Whether the priority field is set.
     */
    boolean hasPriority();

    /**
     * <code>optional int64 priority = 3;</code>
     *
     * @return The priority.
     */
    long getPriority();

    /**
     * <code>optional int64 bizId = 4;</code>
     *
     * @return Whether the bizId field is set.
     */
    boolean hasBizId();

    /**
     * <code>optional int64 bizId = 4;</code>
     *
     * @return The bizId.
     */
    long getBizId();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     *
     * @return Whether the bizType field is set.
     */
    boolean hasBizType();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     *
     * @return The enum numeric value on the wire for bizType.
     */
    int getBizTypeValue();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.PostPanelBizType bizType = 5;</code>
     *
     * @return The bizType.
     */
    PostPanelBizType getBizType();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
     *
     * @return Whether the clickButton field is set.
     */
    boolean hasClickButton();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.ClickButton clickButton = 6;</code>
     *
     * @return The clickButton.
     */
    ClickButton getClickButton();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
     *
     * @return Whether the textInput field is set.
     */
    boolean hasTextInput();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.TextInput textInput = 7;</code>
     *
     * @return The textInput.
     */
    TextInput getTextInput();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
     *
     * @return Whether the checkBox field is set.
     */
    boolean hasCheckBox();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.CheckBox checkBox = 8;</code>
     *
     * @return The checkBox.
     */
    CheckBox getCheckBox();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
     *
     * @return Whether the toast field is set.
     */
    boolean hasToast();

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Toast toast = 9;</code>
     *
     * @return The toast.
     */
    Toast getToast();
}
