// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.TextInput}
 */
public final class TextInput extends
        com.google.protobuf.GeneratedMessageLite<
                TextInput, TextInput.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.TextInput)
        TextInputOrBuilder {
    private TextInput() {
        portraitPlaceholder_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
        landscapePlaceholder_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    private int bitField0_;
    public static final int PORTRAITPLACEHOLDER_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<String> portraitPlaceholder_;

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     *
     * @return A list containing the portraitPlaceholder.
     */
    @Override
    public java.util.List<String> getPortraitPlaceholderList() {
        return portraitPlaceholder_;
    }

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     *
     * @return The count of portraitPlaceholder.
     */
    @Override
    public int getPortraitPlaceholderCount() {
        return portraitPlaceholder_.size();
    }

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The portraitPlaceholder at the given index.
     */
    @Override
    public String getPortraitPlaceholder(int index) {
        return portraitPlaceholder_.get(index);
    }

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the portraitPlaceholder at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
    getPortraitPlaceholderBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
                portraitPlaceholder_.get(index));
    }

    private void ensurePortraitPlaceholderIsMutable() {
        com.google.protobuf.Internal.ProtobufList<String> tmp =
                portraitPlaceholder_;
        if (!tmp.isModifiable()) {
            portraitPlaceholder_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     *
     * @param index The index to set the value at.
     * @param value The portraitPlaceholder to set.
     */
    private void setPortraitPlaceholder(
            int index, String value) {
        Class<?> valueClass = value.getClass();
        ensurePortraitPlaceholderIsMutable();
        portraitPlaceholder_.set(index, value);
    }

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     *
     * @param value The portraitPlaceholder to add.
     */
    private void addPortraitPlaceholder(
            String value) {
        Class<?> valueClass = value.getClass();
        ensurePortraitPlaceholderIsMutable();
        portraitPlaceholder_.add(value);
    }

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     *
     * @param values The portraitPlaceholder to add.
     */
    private void addAllPortraitPlaceholder(
            Iterable<String> values) {
        ensurePortraitPlaceholderIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, portraitPlaceholder_);
    }

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     */
    private void clearPortraitPlaceholder() {
        portraitPlaceholder_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    /**
     * <code>repeated string portraitPlaceholder = 1;</code>
     *
     * @param value The bytes of the portraitPlaceholder to add.
     */
    private void addPortraitPlaceholderBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensurePortraitPlaceholderIsMutable();
        portraitPlaceholder_.add(value.toStringUtf8());
    }

    public static final int LANDSCAPEPLACEHOLDER_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<String> landscapePlaceholder_;

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     *
     * @return A list containing the landscapePlaceholder.
     */
    @Override
    public java.util.List<String> getLandscapePlaceholderList() {
        return landscapePlaceholder_;
    }

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     *
     * @return The count of landscapePlaceholder.
     */
    @Override
    public int getLandscapePlaceholderCount() {
        return landscapePlaceholder_.size();
    }

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The landscapePlaceholder at the given index.
     */
    @Override
    public String getLandscapePlaceholder(int index) {
        return landscapePlaceholder_.get(index);
    }

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the landscapePlaceholder at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
    getLandscapePlaceholderBytes(int index) {
        return com.google.protobuf.ByteString.copyFromUtf8(
                landscapePlaceholder_.get(index));
    }

    private void ensureLandscapePlaceholderIsMutable() {
        com.google.protobuf.Internal.ProtobufList<String> tmp =
                landscapePlaceholder_;
        if (!tmp.isModifiable()) {
            landscapePlaceholder_ =
                    com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
        }
    }

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     *
     * @param index The index to set the value at.
     * @param value The landscapePlaceholder to set.
     */
    private void setLandscapePlaceholder(
            int index, String value) {
        Class<?> valueClass = value.getClass();
        ensureLandscapePlaceholderIsMutable();
        landscapePlaceholder_.set(index, value);
    }

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     *
     * @param value The landscapePlaceholder to add.
     */
    private void addLandscapePlaceholder(
            String value) {
        Class<?> valueClass = value.getClass();
        ensureLandscapePlaceholderIsMutable();
        landscapePlaceholder_.add(value);
    }

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     *
     * @param values The landscapePlaceholder to add.
     */
    private void addAllLandscapePlaceholder(
            Iterable<String> values) {
        ensureLandscapePlaceholderIsMutable();
        com.google.protobuf.AbstractMessageLite.addAll(
                values, landscapePlaceholder_);
    }

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     */
    private void clearLandscapePlaceholder() {
        landscapePlaceholder_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }

    /**
     * <code>repeated string landscapePlaceholder = 2;</code>
     *
     * @param value The bytes of the landscapePlaceholder to add.
     */
    private void addLandscapePlaceholderBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        ensureLandscapePlaceholderIsMutable();
        landscapePlaceholder_.add(value.toStringUtf8());
    }

    public static final int RENDERTYPE_FIELD_NUMBER = 3;
    private int renderType_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
     *
     * @return Whether the renderType field is set.
     */
    @Override
    public boolean hasRenderType() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
     *
     * @return The enum numeric value on the wire for renderType.
     */
    @Override
    public int getRenderTypeValue() {
        return renderType_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
     *
     * @return The renderType.
     */
    @Override
    public RenderType getRenderType() {
        RenderType result = RenderType.forNumber(renderType_);
        return result == null ? RenderType.UNRECOGNIZED : result;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
     *
     * @param value The enum numeric value on the wire for renderType to set.
     */
    private void setRenderTypeValue(int value) {
        bitField0_ |= 0x00000001;
        renderType_ = value;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
     *
     * @param value The renderType to set.
     */
    private void setRenderType(RenderType value) {
        renderType_ = value.getNumber();
        bitField0_ |= 0x00000001;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
     */
    private void clearRenderType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        renderType_ = 0;
    }

    public static final int PLACEHOLDERPOST_FIELD_NUMBER = 4;
    private boolean placeholderPost_;

    /**
     * <code>optional bool placeholderPost = 4;</code>
     *
     * @return Whether the placeholderPost field is set.
     */
    @Override
    public boolean hasPlaceholderPost() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional bool placeholderPost = 4;</code>
     *
     * @return The placeholderPost.
     */
    @Override
    public boolean getPlaceholderPost() {
        return placeholderPost_;
    }

    /**
     * <code>optional bool placeholderPost = 4;</code>
     *
     * @param value The placeholderPost to set.
     */
    private void setPlaceholderPost(boolean value) {
        bitField0_ |= 0x00000002;
        placeholderPost_ = value;
    }

    /**
     * <code>optional bool placeholderPost = 4;</code>
     */
    private void clearPlaceholderPost() {
        bitField0_ = (bitField0_ & ~0x00000002);
        placeholderPost_ = false;
    }

    public static final int SHOW_FIELD_NUMBER = 5;
    private boolean show_;

    /**
     * <code>optional bool show = 5;</code>
     *
     * @return Whether the show field is set.
     */
    @Override
    public boolean hasShow() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>optional bool show = 5;</code>
     *
     * @return The show.
     */
    @Override
    public boolean getShow() {
        return show_;
    }

    /**
     * <code>optional bool show = 5;</code>
     *
     * @param value The show to set.
     */
    private void setShow(boolean value) {
        bitField0_ |= 0x00000004;
        show_ = value;
    }

    /**
     * <code>optional bool show = 5;</code>
     */
    private void clearShow() {
        bitField0_ = (bitField0_ & ~0x00000004);
        show_ = false;
    }

    public static TextInput parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static TextInput parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static TextInput parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static TextInput parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static TextInput parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static TextInput parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static TextInput parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static TextInput parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static TextInput parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static TextInput parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static TextInput parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static TextInput parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(TextInput prototype) {
        return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.TextInput}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    TextInput, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.TextInput)
            TextInputOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.TextInput.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @return A list containing the portraitPlaceholder.
         */
        @Override
        public java.util.List<String>
        getPortraitPlaceholderList() {
            return java.util.Collections.unmodifiableList(
                    instance.getPortraitPlaceholderList());
        }

        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @return The count of portraitPlaceholder.
         */
        @Override
        public int getPortraitPlaceholderCount() {
            return instance.getPortraitPlaceholderCount();
        }

        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The portraitPlaceholder at the given index.
         */
        @Override
        public String getPortraitPlaceholder(int index) {
            return instance.getPortraitPlaceholder(index);
        }

        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the portraitPlaceholder at the given index.
         */
        @Override
        public com.google.protobuf.ByteString
        getPortraitPlaceholderBytes(int index) {
            return instance.getPortraitPlaceholderBytes(index);
        }

        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @param index The index to set the value at.
         * @param value The portraitPlaceholder to set.
         * @return This builder for chaining.
         */
        public Builder setPortraitPlaceholder(
                int index, String value) {
            copyOnWrite();
            instance.setPortraitPlaceholder(index, value);
            return this;
        }

        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @param value The portraitPlaceholder to add.
         * @return This builder for chaining.
         */
        public Builder addPortraitPlaceholder(
                String value) {
            copyOnWrite();
            instance.addPortraitPlaceholder(value);
            return this;
        }

        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @param values The portraitPlaceholder to add.
         * @return This builder for chaining.
         */
        public Builder addAllPortraitPlaceholder(
                Iterable<String> values) {
            copyOnWrite();
            instance.addAllPortraitPlaceholder(values);
            return this;
        }

        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPortraitPlaceholder() {
            copyOnWrite();
            instance.clearPortraitPlaceholder();
            return this;
        }

        /**
         * <code>repeated string portraitPlaceholder = 1;</code>
         *
         * @param value The bytes of the portraitPlaceholder to add.
         * @return This builder for chaining.
         */
        public Builder addPortraitPlaceholderBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.addPortraitPlaceholderBytes(value);
            return this;
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @return A list containing the landscapePlaceholder.
         */
        @Override
        public java.util.List<String>
        getLandscapePlaceholderList() {
            return java.util.Collections.unmodifiableList(
                    instance.getLandscapePlaceholderList());
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @return The count of landscapePlaceholder.
         */
        @Override
        public int getLandscapePlaceholderCount() {
            return instance.getLandscapePlaceholderCount();
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @param index The index of the element to return.
         * @return The landscapePlaceholder at the given index.
         */
        @Override
        public String getLandscapePlaceholder(int index) {
            return instance.getLandscapePlaceholder(index);
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the landscapePlaceholder at the given index.
         */
        @Override
        public com.google.protobuf.ByteString
        getLandscapePlaceholderBytes(int index) {
            return instance.getLandscapePlaceholderBytes(index);
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @param index The index to set the value at.
         * @param value The landscapePlaceholder to set.
         * @return This builder for chaining.
         */
        public Builder setLandscapePlaceholder(
                int index, String value) {
            copyOnWrite();
            instance.setLandscapePlaceholder(index, value);
            return this;
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @param value The landscapePlaceholder to add.
         * @return This builder for chaining.
         */
        public Builder addLandscapePlaceholder(
                String value) {
            copyOnWrite();
            instance.addLandscapePlaceholder(value);
            return this;
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @param values The landscapePlaceholder to add.
         * @return This builder for chaining.
         */
        public Builder addAllLandscapePlaceholder(
                Iterable<String> values) {
            copyOnWrite();
            instance.addAllLandscapePlaceholder(values);
            return this;
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLandscapePlaceholder() {
            copyOnWrite();
            instance.clearLandscapePlaceholder();
            return this;
        }

        /**
         * <code>repeated string landscapePlaceholder = 2;</code>
         *
         * @param value The bytes of the landscapePlaceholder to add.
         * @return This builder for chaining.
         */
        public Builder addLandscapePlaceholderBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.addLandscapePlaceholderBytes(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
         *
         * @return Whether the renderType field is set.
         */
        @Override
        public boolean hasRenderType() {
            return instance.hasRenderType();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
         *
         * @return The enum numeric value on the wire for renderType.
         */
        @Override
        public int getRenderTypeValue() {
            return instance.getRenderTypeValue();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
         *
         * @param value The renderType to set.
         * @return This builder for chaining.
         */
        public Builder setRenderTypeValue(int value) {
            copyOnWrite();
            instance.setRenderTypeValue(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
         *
         * @return The renderType.
         */
        @Override
        public RenderType getRenderType() {
            return instance.getRenderType();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
         *
         * @param value The enum numeric value on the wire for renderType to set.
         * @return This builder for chaining.
         */
        public Builder setRenderType(RenderType value) {
            copyOnWrite();
            instance.setRenderType(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.RenderType renderType = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearRenderType() {
            copyOnWrite();
            instance.clearRenderType();
            return this;
        }

        /**
         * <code>optional bool placeholderPost = 4;</code>
         *
         * @return Whether the placeholderPost field is set.
         */
        @Override
        public boolean hasPlaceholderPost() {
            return instance.hasPlaceholderPost();
        }

        /**
         * <code>optional bool placeholderPost = 4;</code>
         *
         * @return The placeholderPost.
         */
        @Override
        public boolean getPlaceholderPost() {
            return instance.getPlaceholderPost();
        }

        /**
         * <code>optional bool placeholderPost = 4;</code>
         *
         * @param value The placeholderPost to set.
         * @return This builder for chaining.
         */
        public Builder setPlaceholderPost(boolean value) {
            copyOnWrite();
            instance.setPlaceholderPost(value);
            return this;
        }

        /**
         * <code>optional bool placeholderPost = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPlaceholderPost() {
            copyOnWrite();
            instance.clearPlaceholderPost();
            return this;
        }

        /**
         * <code>optional bool show = 5;</code>
         *
         * @return Whether the show field is set.
         */
        @Override
        public boolean hasShow() {
            return instance.hasShow();
        }

        /**
         * <code>optional bool show = 5;</code>
         *
         * @return The show.
         */
        @Override
        public boolean getShow() {
            return instance.getShow();
        }

        /**
         * <code>optional bool show = 5;</code>
         *
         * @param value The show to set.
         * @return This builder for chaining.
         */
        public Builder setShow(boolean value) {
            copyOnWrite();
            instance.setShow(value);
            return this;
        }

        /**
         * <code>optional bool show = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearShow() {
            copyOnWrite();
            instance.clearShow();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.TextInput)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new TextInput();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "portraitPlaceholder_",
                        "landscapePlaceholder_",
                        "renderType_",
                        "placeholderPost_",
                        "show_",
                };
                String info =
                        "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0002\u0000\u0001\u021a\u0002\u021a" +
                                "\u0003\u100c\u0000\u0004\u1007\u0001\u0005\u1007\u0002";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<TextInput> parser = PARSER;
                if (parser == null) {
                    synchronized (TextInput.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<TextInput>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.TextInput)
    private static final TextInput DEFAULT_INSTANCE;

    static {
        TextInput defaultInstance = new TextInput();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                TextInput.class, defaultInstance);
    }

    public static TextInput getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TextInput> PARSER;

    public static com.google.protobuf.Parser<TextInput> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

