// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf enum {@code com.muedsa.bilibililiveapiclient.model.ToastFunctionType}
 */
public enum ToastFunctionType
        implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ToastFunctionTypeNone = 0;</code>
     */
    ToastFunctionTypeNone(0),
    /**
     * <code>ToastFunctionTypePostPanel = 1;</code>
     */
    ToastFunctionTypePostPanel(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ToastFunctionTypeNone = 0;</code>
     */
    public static final int ToastFunctionTypeNone_VALUE = 0;
    /**
     * <code>ToastFunctionTypePostPanel = 1;</code>
     */
    public static final int ToastFunctionTypePostPanel_VALUE = 1;


    @Override
    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ToastFunctionType valueOf(int value) {
        return forNumber(value);
    }

    public static ToastFunctionType forNumber(int value) {
        switch (value) {
            case 0:
                return ToastFunctionTypeNone;
            case 1:
                return ToastFunctionTypePostPanel;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ToastFunctionType>
    internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            ToastFunctionType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ToastFunctionType>() {
                @Override
                public ToastFunctionType findValueByNumber(int number) {
                    return ToastFunctionType.forNumber(number);
                }
            };

    public static com.google.protobuf.Internal.EnumVerifier
    internalGetVerifier() {
        return ToastFunctionTypeVerifier.INSTANCE;
    }

    private static final class ToastFunctionTypeVerifier implements
            com.google.protobuf.Internal.EnumVerifier {
        static final com.google.protobuf.Internal.EnumVerifier INSTANCE = new ToastFunctionTypeVerifier();

        @Override
        public boolean isInRange(int number) {
            return ToastFunctionType.forNumber(number) != null;
        }
    }

    ;

    private final int value;

    private ToastFunctionType(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.muedsa.bilibililiveapiclient.model.ToastFunctionType)
}

