// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: danmaku.proto

package com.muedsa.bilibililiveapiclient.model.danmaku;

/**
 * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Toast}
 */
public final class Toast extends
        com.google.protobuf.GeneratedMessageLite<
                Toast, Toast.Builder> implements
        // @@protoc_insertion_point(message_implements:com.muedsa.bilibililiveapiclient.model.Toast)
        ToastOrBuilder {
    private Toast() {
        text_ = "";
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private String text_;

    /**
     * <code>optional string text = 1;</code>
     *
     * @return Whether the text field is set.
     */
    @Override
    public boolean hasText() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional string text = 1;</code>
     *
     * @return The text.
     */
    @Override
    public String getText() {
        return text_;
    }

    /**
     * <code>optional string text = 1;</code>
     *
     * @return The bytes for text.
     */
    @Override
    public com.google.protobuf.ByteString
    getTextBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(text_);
    }

    /**
     * <code>optional string text = 1;</code>
     *
     * @param value The text to set.
     */
    private void setText(
            String value) {
        Class<?> valueClass = value.getClass();
        bitField0_ |= 0x00000001;
        text_ = value;
    }

    /**
     * <code>optional string text = 1;</code>
     */
    private void clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
    }

    /**
     * <code>optional string text = 1;</code>
     *
     * @param value The bytes for text to set.
     */
    private void setTextBytes(
            com.google.protobuf.ByteString value) {
        checkByteStringIsUtf8(value);
        text_ = value.toStringUtf8();
        bitField0_ |= 0x00000001;
    }

    public static final int DURATION_FIELD_NUMBER = 2;
    private int duration_;

    /**
     * <code>optional int32 duration = 2;</code>
     *
     * @return Whether the duration field is set.
     */
    @Override
    public boolean hasDuration() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional int32 duration = 2;</code>
     *
     * @return The duration.
     */
    @Override
    public int getDuration() {
        return duration_;
    }

    /**
     * <code>optional int32 duration = 2;</code>
     *
     * @param value The duration to set.
     */
    private void setDuration(int value) {
        bitField0_ |= 0x00000002;
        duration_ = value;
    }

    /**
     * <code>optional int32 duration = 2;</code>
     */
    private void clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000002);
        duration_ = 0;
    }

    public static final int SHOW_FIELD_NUMBER = 3;
    private boolean show_;

    /**
     * <code>optional bool show = 3;</code>
     *
     * @return Whether the show field is set.
     */
    @Override
    public boolean hasShow() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>optional bool show = 3;</code>
     *
     * @return The show.
     */
    @Override
    public boolean getShow() {
        return show_;
    }

    /**
     * <code>optional bool show = 3;</code>
     *
     * @param value The show to set.
     */
    private void setShow(boolean value) {
        bitField0_ |= 0x00000004;
        show_ = value;
    }

    /**
     * <code>optional bool show = 3;</code>
     */
    private void clearShow() {
        bitField0_ = (bitField0_ & ~0x00000004);
        show_ = false;
    }

    public static final int BUTTON_FIELD_NUMBER = 4;
    private Button button_;

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
     */
    @Override
    public boolean hasButton() {
        return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
     */
    @Override
    public Button getButton() {
        return button_ == null ? Button.getDefaultInstance() : button_;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
     */
    private void setButton(Button value) {
        value.getClass();
        button_ = value;
        bitField0_ |= 0x00000008;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeButton(Button value) {
        value.getClass();
        if (button_ != null &&
                button_ != Button.getDefaultInstance()) {
            button_ =
                    Button.newBuilder(button_).mergeFrom(value).buildPartial();
        } else {
            button_ = value;
        }
        bitField0_ |= 0x00000008;
    }

    /**
     * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
     */
    private void clearButton() {
        button_ = null;
        bitField0_ = (bitField0_ & ~0x00000008);
    }

    public static Toast parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Toast parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Toast parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Toast parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Toast parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data);
    }

    public static Toast parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static Toast parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Toast parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Toast parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static Toast parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Toast parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input);
    }

    public static Toast parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
                DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(Toast prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.muedsa.bilibililiveapiclient.model.Toast}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageLite.Builder<
                    Toast, Builder> implements
            // @@protoc_insertion_point(builder_implements:com.muedsa.bilibililiveapiclient.model.Toast)
            ToastOrBuilder {
        // Construct using com.muedsa.bilibililiveapiclient.model.danmaku.Toast.newBuilder()
        private Builder() {
            super(DEFAULT_INSTANCE);
        }


        /**
         * <code>optional string text = 1;</code>
         *
         * @return Whether the text field is set.
         */
        @Override
        public boolean hasText() {
            return instance.hasText();
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @return The text.
         */
        @Override
        public String getText() {
            return instance.getText();
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @return The bytes for text.
         */
        @Override
        public com.google.protobuf.ByteString
        getTextBytes() {
            return instance.getTextBytes();
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @param value The text to set.
         * @return This builder for chaining.
         */
        public Builder setText(
                String value) {
            copyOnWrite();
            instance.setText(value);
            return this;
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearText() {
            copyOnWrite();
            instance.clearText();
            return this;
        }

        /**
         * <code>optional string text = 1;</code>
         *
         * @param value The bytes for text to set.
         * @return This builder for chaining.
         */
        public Builder setTextBytes(
                com.google.protobuf.ByteString value) {
            copyOnWrite();
            instance.setTextBytes(value);
            return this;
        }

        /**
         * <code>optional int32 duration = 2;</code>
         *
         * @return Whether the duration field is set.
         */
        @Override
        public boolean hasDuration() {
            return instance.hasDuration();
        }

        /**
         * <code>optional int32 duration = 2;</code>
         *
         * @return The duration.
         */
        @Override
        public int getDuration() {
            return instance.getDuration();
        }

        /**
         * <code>optional int32 duration = 2;</code>
         *
         * @param value The duration to set.
         * @return This builder for chaining.
         */
        public Builder setDuration(int value) {
            copyOnWrite();
            instance.setDuration(value);
            return this;
        }

        /**
         * <code>optional int32 duration = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDuration() {
            copyOnWrite();
            instance.clearDuration();
            return this;
        }

        /**
         * <code>optional bool show = 3;</code>
         *
         * @return Whether the show field is set.
         */
        @Override
        public boolean hasShow() {
            return instance.hasShow();
        }

        /**
         * <code>optional bool show = 3;</code>
         *
         * @return The show.
         */
        @Override
        public boolean getShow() {
            return instance.getShow();
        }

        /**
         * <code>optional bool show = 3;</code>
         *
         * @param value The show to set.
         * @return This builder for chaining.
         */
        public Builder setShow(boolean value) {
            copyOnWrite();
            instance.setShow(value);
            return this;
        }

        /**
         * <code>optional bool show = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearShow() {
            copyOnWrite();
            instance.clearShow();
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
         */
        @Override
        public boolean hasButton() {
            return instance.hasButton();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
         */
        @Override
        public Button getButton() {
            return instance.getButton();
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
         */
        public Builder setButton(Button value) {
            copyOnWrite();
            instance.setButton(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
         */
        public Builder setButton(
                Button.Builder builderForValue) {
            copyOnWrite();
            instance.setButton(builderForValue.build());
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
         */
        public Builder mergeButton(Button value) {
            copyOnWrite();
            instance.mergeButton(value);
            return this;
        }

        /**
         * <code>optional .com.muedsa.bilibililiveapiclient.model.Button button = 4;</code>
         */
        public Builder clearButton() {
            copyOnWrite();
            instance.clearButton();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.muedsa.bilibililiveapiclient.model.Toast)
    }

    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
            MethodToInvoke method,
            Object arg0, Object arg1) {
        switch (method) {
            case NEW_MUTABLE_INSTANCE: {
                return new Toast();
            }
            case NEW_BUILDER: {
                return new Builder();
            }
            case BUILD_MESSAGE_INFO: {
                Object[] objects = new Object[]{
                        "bitField0_",
                        "text_",
                        "duration_",
                        "show_",
                        "button_",
                };
                String info =
                        "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u1208\u0000\u0002" +
                                "\u1004\u0001\u0003\u1007\u0002\u0004\u1009\u0003";
                return newMessageInfo(DEFAULT_INSTANCE, info, objects);
            }
            // fall through
            case GET_DEFAULT_INSTANCE: {
                return DEFAULT_INSTANCE;
            }
            case GET_PARSER: {
                com.google.protobuf.Parser<Toast> parser = PARSER;
                if (parser == null) {
                    synchronized (Toast.class) {
                        parser = PARSER;
                        if (parser == null) {
                            parser =
                                    new DefaultInstanceBasedParser<Toast>(
                                            DEFAULT_INSTANCE);
                            PARSER = parser;
                        }
                    }
                }
                return parser;
            }
            case GET_MEMOIZED_IS_INITIALIZED: {
                return (byte) 1;
            }
            case SET_MEMOIZED_IS_INITIALIZED: {
                return null;
            }
        }
        throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.muedsa.bilibililiveapiclient.model.Toast)
    private static final Toast DEFAULT_INSTANCE;

    static {
        Toast defaultInstance = new Toast();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
                Toast.class, defaultInstance);
    }

    public static Toast getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Toast> PARSER;

    public static com.google.protobuf.Parser<Toast> parser() {
        return DEFAULT_INSTANCE.getParserForType();
    }
}

